run := if env("BOOTH_CONTAINER_NAME", "") == "" { "./booth exec --run --" } else { "" }

[private]
default:
    @just --list

# Drive the same Playwright task from five languages
run:
    {{run}} ./run-polyglot.sh

alias test := run
