<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net9.0</TargetFramework>
    <CheckEoSForRuntimeIdentifiers />
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="Program.fs" />
  </ItemGroup>
  <ItemGroup>
    <None Include="customers.csv" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
