run := if env("BOOTH_CONTAINER_NAME", "") == "" { "./booth exec --run --" } else { "" }

[private]
default:
    @just --list

# Compile the Maven sample (`jenv local 21` first to pick a JDK)
build:
    {{run}} mvn -q compile
