// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Counter is the Go service the frontend calls. The number lives here, not in JS.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

export function Increment(): $CancellablePromise<number> {
    return $Call.ByID(3623214804);
}

export function Reset(): $CancellablePromise<number> {
    return $Call.ByID(777025534);
}

export function Value(): $CancellablePromise<number> {
    return $Call.ByID(2748870884);
}
