display-name = "Go VS Code Extension"
display-disc = "Go language support for VS Code"
display-order = 2
auto-select = true
tags = [
    "go",
    "ide",
    "vscode",
]

[segments]
Boothfile = """
setup go-code-extension
"""
