display-name = "sqluv"
display-disc = "Terminal UI for MySQL/PostgreSQL/SQLite3/SQL Server and CSV/TSV/LTSV"
display-detail = "Installs sqluv, a simple terminal UI for querying RDBMS (MySQL, PostgreSQL, SQLite3, SQL Server) as well as local, HTTPS, or S3 CSV/TSV/LTSV files with SQL. Connections are entered interactively and saved for later launches."
display-order = 73
tags = [
    "database",
    "sql",
    "tui",
    "cli",
]

[params.SQLUV_VERSION]
default = "latest"
suggests = ["latest", "0.4.8"]

[segments]
Boothfile = """
setup sqluv --version ${SQLUV_VERSION}
"""
