# NOTE: This template has not been tested -- no time (sorry). Please report success or failure. :-p
display-name = "Haskell VS Code Extension"
display-disc = "Haskell language support for VS Code"
display-order = 1
auto-select = true
tags = [
    "haskell",
    "ide",
    "vscode",
]

[segments]
"Boothfile--65" = """
setup haskell-code-extension
"""
