#!/bin/bash
source "$(dirname "$0")/test-helpers--source.sh"

begin

# Test 1: Template with startup creates startups/ directory
run booth init new $prj --select "excalidraw+autostart"
startups_dir="$prj/.booth/startups"
TEST_COUNT=$((TEST_COUNT + 1))
label="startups/ directory created "
pad=$(printf '%*s' $((64 - ${#label})) '' | tr ' ' '.')
echo -n "Test ${TEST_COUNT}: ${label}${pad} "
if [ -d "$startups_dir" ]; then
    PASS_COUNT=$((PASS_COUNT + 1))
    echo -e "\033[32mPASSED\033[0m"
else
    FAIL_COUNT=$((FAIL_COUNT + 1))
    FAIL_TESTS+=("Test ${TEST_COUNT}: ${label}")
    echo -e "\033[31mFAILED\033[0m"
    echo "  EXPECTED: directory $startups_dir to exist"
fi

# Test 2: Startup file has correct name with order prefix
startup="$startups_dir/65-excalidraw-autostart--startup.sh"
TEST_COUNT=$((TEST_COUNT + 1))
label="startup file has order prefix "
pad=$(printf '%*s' $((64 - ${#label})) '' | tr ' ' '.')
echo -n "Test ${TEST_COUNT}: ${label}${pad} "
if [ -f "$startup" ]; then
    PASS_COUNT=$((PASS_COUNT + 1))
    echo -e "\033[32mPASSED\033[0m"
else
    FAIL_COUNT=$((FAIL_COUNT + 1))
    FAIL_TESTS+=("Test ${TEST_COUNT}: ${label}")
    echo -e "\033[31mFAILED\033[0m"
    echo "  EXPECTED: file $startup to exist"
fi

# Test 3: Startup file has shebang header
assert-line "$startup" '#!/bin/bash' ''  "startup file has shebang"

# Test 4: Startup file has Generated by header
TEST_COUNT=$((TEST_COUNT + 1))
label="startup file has Generated by header "
pad=$(printf '%*s' $((64 - ${#label})) '' | tr ' ' '.')
echo -n "Test ${TEST_COUNT}: ${label}${pad} "
if grep -q "^# Generated by:" "$startup" 2>/dev/null; then
    PASS_COUNT=$((PASS_COUNT + 1))
    echo -e "\033[32mPASSED\033[0m"
else
    FAIL_COUNT=$((FAIL_COUNT + 1))
    FAIL_TESTS+=("Test ${TEST_COUNT}: ${label}")
    echo -e "\033[31mFAILED\033[0m"
    echo "  EXPECTED: line starting with '# Generated by:' in $startup"
fi

# Test 5: Startup file is executable
TEST_COUNT=$((TEST_COUNT + 1))
label="startup file is executable "
pad=$(printf '%*s' $((64 - ${#label})) '' | tr ' ' '.')
echo -n "Test ${TEST_COUNT}: ${label}${pad} "
if [ -x "$startup" ]; then
    PASS_COUNT=$((PASS_COUNT + 1))
    echo -e "\033[32mPASSED\033[0m"
else
    FAIL_COUNT=$((FAIL_COUNT + 1))
    FAIL_TESTS+=("Test ${TEST_COUNT}: ${label}")
    echo -e "\033[31mFAILED\033[0m"
    echo "  EXPECTED: $startup to be executable"
fi

# Test 6: No startup.sh generated (replaced by startups/)
TEST_COUNT=$((TEST_COUNT + 1))
label="no startup.sh generated "
pad=$(printf '%*s' $((64 - ${#label})) '' | tr ' ' '.')
echo -n "Test ${TEST_COUNT}: ${label}${pad} "
if [ ! -f "$prj/.booth/startup.sh" ]; then
    PASS_COUNT=$((PASS_COUNT + 1))
    echo -e "\033[32mPASSED\033[0m"
else
    FAIL_COUNT=$((FAIL_COUNT + 1))
    FAIL_TESTS+=("Test ${TEST_COUNT}: ${label}")
    echo -e "\033[31mFAILED\033[0m"
    echo "  EXPECTED: $prj/.booth/startup.sh should not exist"
fi

# Test 7: Multiple startup segments produce multiple files
run rm -Rf $prj
mkdir -p $prj
run booth init new $prj --select "claude-code+auto-accept/excalidraw+autostart"
startups_dir="$prj/.booth/startups"
file_count=$(ls "$startups_dir"/*--startup.sh 2>/dev/null | wc -l)
TEST_COUNT=$((TEST_COUNT + 1))
label="multiple startups produce multiple files "
pad=$(printf '%*s' $((64 - ${#label})) '' | tr ' ' '.')
echo -n "Test ${TEST_COUNT}: ${label}${pad} "
if [ "$file_count" -ge 2 ]; then
    PASS_COUNT=$((PASS_COUNT + 1))
    echo -e "\033[32mPASSED\033[0m"
else
    FAIL_COUNT=$((FAIL_COUNT + 1))
    FAIL_TESTS+=("Test ${TEST_COUNT}: ${label}")
    echo -e "\033[31mFAILED\033[0m"
    echo "  EXPECTED: >= 2 startup files, FOUND: $file_count"
fi

# Test 8: Adjust cleans up stale generated files
run rm -Rf $prj
mkdir -p $prj
run booth init new $prj --select "excalidraw+autostart"
# Verify excalidraw startup exists
assert-line "$prj/.booth/startups/65-excalidraw-autostart--startup.sh" '#!/bin/bash' ''  "pre-adjust: excalidraw startup exists"
# Now adjust without excalidraw — the old startup file should be cleaned up
run booth init adjust $prj --select "go"
TEST_COUNT=$((TEST_COUNT + 1))
label="adjust removes stale generated startups "
pad=$(printf '%*s' $((64 - ${#label})) '' | tr ' ' '.')
echo -n "Test ${TEST_COUNT}: ${label}${pad} "
if [ ! -f "$prj/.booth/startups/65-excalidraw-autostart--startup.sh" ]; then
    PASS_COUNT=$((PASS_COUNT + 1))
    echo -e "\033[32mPASSED\033[0m"
else
    FAIL_COUNT=$((FAIL_COUNT + 1))
    FAIL_TESTS+=("Test ${TEST_COUNT}: ${label}")
    echo -e "\033[31mFAILED\033[0m"
    echo "  EXPECTED: stale startup file to be removed after adjust"
fi

# Test 9: Template without startup doesn't create startups/ dir
run rm -Rf $prj
mkdir -p $prj
run booth init new $prj --select "go"
TEST_COUNT=$((TEST_COUNT + 1))
label="no startups/ for template without startup "
pad=$(printf '%*s' $((64 - ${#label})) '' | tr ' ' '.')
echo -n "Test ${TEST_COUNT}: ${label}${pad} "
if [ ! -d "$prj/.booth/startups" ]; then
    PASS_COUNT=$((PASS_COUNT + 1))
    echo -e "\033[32mPASSED\033[0m"
else
    FAIL_COUNT=$((FAIL_COUNT + 1))
    FAIL_TESTS+=("Test ${TEST_COUNT}: ${label}")
    echo -e "\033[31mFAILED\033[0m"
    echo "  EXPECTED: startups/ directory should not exist for go template"
fi

finally
