display-name = "Expose Excalidraw Port"
display-disc = "Expose Excalidraw port to host network"
display-order = 1
auto-select = false
tags = [
    "excalidraw",
    "port",
    "network"
]

run-args = [
    "-p", "15555:15555",
]
