#!/usr/bin/env bash
# Copyright 2025-2026 : Nawa Manusitthipol
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.

# i3-ctrl-alt--setup.sh — a Ctrl+Alt twin for every i3 mod-key binding.
#
# Run after i3--setup.sh (the i3 template's +ctrl-alt extension). Alt (and
# Super) combos only reach the booth in a browser that can capture the keyboard
# — the panel's Full screen button, Chromium only. Firefox keeps Alt+letter for
# its menus and Alt+arrows for Back/Forward, but passes Ctrl+Alt+letter/digit
# through. So each top-level `bindsym $mod+…` in /etc/xdg/i3/config gets a
# `bindsym Control+Mod1+…` twin in /etc/xdg/i3/config.d/ctrl-alt.conf.
# floating_modifier takes a single key, so dragging a floating window stays
# mod+drag (or drag its title bar).
#
# Also:
#   - The desktop's own Ctrl+Alt shortcuts that would race i3 are dropped from
#     the system default — XFCE: Ctrl+Alt+l (lock) and Ctrl+Alt+f (Thunar);
#     LXQt: Ctrl+Alt+L (lock) and Ctrl+Alt+E (file manager). Locking an
#     in-browser booth only hides it, and the file manager is on the panel/dock.
#     Homes that already have a shortcuts file keep it.
#   - The Help dialog's i3 tab lists the Ctrl+Alt forms (i3-00-ctrl-alt.js sets
#     window.CB_I3_KEYS before i3-help.js reads it; plugins load in name order).
#
# Usage: i3-ctrl-alt--setup.sh
set -Eeuo pipefail
trap 'echo "❌ Error on line $LINENO" >&2; exit 1' ERR

SCRIPT_NAME="$(basename "$0")"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

if [[ $EUID -ne 0 ]]; then
  echo "❌ This script must be run as root" >&2
  exit 1
fi

source "$SCRIPT_DIR/libs/skip-setup.sh"
I3_CONFIG=/etc/xdg/i3/config
if ! command -v i3 &>/dev/null || [[ ! -f "$I3_CONFIG" ]]; then
  skip_setup "$SCRIPT_NAME" "i3 is not set up (i3--setup.sh skipped or has not run)"
fi

install -d -m 0755 /etc/xdg/i3/config.d
{
  echo "# Ctrl+Alt twins of the \$mod bindings in /etc/xdg/i3/config."
  echo "# Generated by i3-ctrl-alt--setup.sh — regenerate rather than edit."
  sed -n 's/^bindsym \$mod+/bindsym Control+Mod1+/p' "$I3_CONFIG"
} > /etc/xdg/i3/config.d/ctrl-alt.conf
chmod 0644 /etc/xdg/i3/config.d/ctrl-alt.conf

if ! grep -q '^bindsym Control+Mod1+h focus left$' /etc/xdg/i3/config.d/ctrl-alt.conf; then
  echo "❌ No Ctrl+Alt twins generated from ${I3_CONFIG}" >&2
  exit 2
fi
if ! i3 -C -c "$I3_CONFIG" >/dev/null; then
  i3 -C -c "$I3_CONFIG" >&2 || true
  echo "❌ ${I3_CONFIG} does not validate with ctrl-alt.conf" >&2
  exit 2
fi

# ---- the desktop's clashing Ctrl+Alt shortcuts ----
XFCE_KEYS=/etc/xdg/xfce4/xfconf/xfce-perchannel-xml/xfce4-keyboard-shortcuts.xml
if [[ -f "$XFCE_KEYS" ]]; then
  sed -i -E '/<property name="&lt;Primary&gt;&lt;Alt&gt;[lf]" type="string"/d' "$XFCE_KEYS"
fi
# LXQt keeps its defaults in a directory of that name on Ubuntu; accept either.
for LXQT_KEYS in /etc/xdg/lxqt/globalkeyshortcuts.conf/globalkeyshortcuts.conf /etc/xdg/lxqt/globalkeyshortcuts.conf; do
  [[ -f "$LXQT_KEYS" ]] || continue
  sed -i -E '/^\[Control%2BAlt%2B[EL]\.[0-9]+\]$/,/^\[/ s/^Enabled=true$/Enabled=false/' "$LXQT_KEYS"
done

# ---- Help lists the Ctrl+Alt forms ----
PLUGIN_DIR=/usr/local/share/booth-message-wrapper/plugins
if [[ -d "$PLUGIN_DIR" ]]; then
  cat > "$PLUGIN_DIR/i3-00-ctrl-alt.js" <<'EOF'
// Installed by i3-ctrl-alt--setup.sh: the i3 Help tab (i3-help.js, loaded
// after this file) lists its shortcuts with Ctrl+Alt, which every browser passes.
window.CB_I3_KEYS = "Ctrl+Alt";
EOF
  chmod 0644 "$PLUGIN_DIR/i3-00-ctrl-alt.js"
fi

echo "✅ $(grep -c '^bindsym' /etc/xdg/i3/config.d/ctrl-alt.conf) Ctrl+Alt twins in /etc/xdg/i3/config.d/ctrl-alt.conf"
