#!/usr/bin/env bash
# Copyright 2025-2026 : Nawa Manusitthipol
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.

# sway-ctrl-alt--setup.sh — a Ctrl+Alt twin for every sway mod-key shortcut.
#
# Run after sway--setup.sh (the sway template's +ctrl-alt extension). Alt
# shortcuts only reach the booth when the browser lets go of them — Chrome with
# the panel's Full screen on; Firefox keeps Alt for its own menus. Ctrl+Alt
# gets through every browser, so each `bindsym $mod+…` in /etc/sway/config gets
# a `bindsym Ctrl+Mod1+…` twin in /etc/sway/config.d/ctrl-alt.conf, and the
# Help dialog's sway tab lists the Ctrl+Alt forms (sway-00-ctrl-alt.js sets
# window.CB_SWAY_KEYS before sway-help.js reads it; plugins load in name order).
#
# Usage: sway-ctrl-alt--setup.sh
set -Eeuo pipefail
trap 'echo "❌ Error on line $LINENO" >&2; exit 1' ERR

SCRIPT_NAME="$(basename "$0")"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

if [[ $EUID -ne 0 ]]; then
  echo "❌ This script must be run as root" >&2
  exit 1
fi

source "$SCRIPT_DIR/libs/skip-setup.sh"
SWAY_CONFIG=/etc/sway/config
if ! command -v sway &>/dev/null || [[ ! -f /opt/codingbooth/wayland-compositor ]]; then
  skip_setup "$SCRIPT_NAME" "sway is not set up (sway--setup.sh skipped or has not run)"
fi

install -d -m 0755 /etc/sway/config.d
{
  echo "# Ctrl+Alt twins of the \$mod bindings in /etc/sway/config."
  echo "# Generated by sway-ctrl-alt--setup.sh — regenerate rather than edit."
  sed -n 's/^bindsym \$mod+/bindsym Ctrl+Mod1+/p' "$SWAY_CONFIG"
} > /etc/sway/config.d/ctrl-alt.conf
chmod 0644 /etc/sway/config.d/ctrl-alt.conf

if ! grep -q '^bindsym Ctrl+Mod1+h focus left$' /etc/sway/config.d/ctrl-alt.conf; then
  echo "❌ No Ctrl+Alt twins generated from ${SWAY_CONFIG}" >&2
  exit 2
fi
# See sway--setup.sh for why validating needs these.
dir="$(mktemp -d)"
if ! XDG_RUNTIME_DIR="$dir" WLR_BACKENDS=headless WLR_RENDERER=pixman \
     sway --unsupported-gpu -C -c "$SWAY_CONFIG" >/dev/null 2>&1; then
  rm -rf "$dir"
  echo "❌ ${SWAY_CONFIG} does not validate with ctrl-alt.conf" >&2
  exit 2
fi
rm -rf "$dir"

# ---- Help lists the Ctrl+Alt forms ----
PLUGIN_DIR=/usr/local/share/booth-message-wrapper/plugins
if [[ -d "$PLUGIN_DIR" ]]; then
  cat > "$PLUGIN_DIR/sway-00-ctrl-alt.js" <<'JS'
// Installed by sway-ctrl-alt--setup.sh: the sway Help tab (sway-help.js, loaded
// after this file) lists its shortcuts with Ctrl+Alt, which every browser passes.
window.CB_SWAY_KEYS = "Ctrl+Alt";
JS
  chmod 0644 "$PLUGIN_DIR/sway-00-ctrl-alt.js"
fi

echo "✅ $(grep -c '^bindsym' /etc/sway/config.d/ctrl-alt.conf) Ctrl+Alt twins in /etc/sway/config.d/ctrl-alt.conf"
