display-name = "uv"
display-disc = "Fast Python package manager"
display-order = 10
auto-select = false
tags = [
    "python",
    "packages"
]

[segments]
Boothfile = """
# uv is already installed by python setup.
# This extension enables 'install uv <packages>' in Boothfiles.
"""
"Boothfile--90" = """
copy .booth/requirements.txt /tmp/requirements.txt
run uv pip install -r /tmp/requirements.txt
"""
