#!/usr/bin/env bash
# Copyright 2025-2026 : Nawa Manusitthipol
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.

# -----------------------------------------------------------------------------
# Test: Project-local setup / template / extension
#
# Exercises the three project-owned layers together:
#
#   1. Local template  — .booth/templates/project/localgadget/
#   2. Local extension — localgadget+widget (widget--extension.toml)
#   3. Local setup     — hand-placed .booth/setups/local-hand--setup.sh
#                        (referenced by the template, not generated by it)
#
# Detection markers (unique strings, easy to grep):
#   CB_DETECT_TEMPLATE_v1   — template setup + Boothfile comment
#   CB_DETECT_EXTENSION_v1  — extension setup + Boothfile comment
#   CB_DETECT_SETUP_v1      — hand-placed local setup
# -----------------------------------------------------------------------------

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$SCRIPT_DIR"

source ../../common--source.sh

echo "=== Test: Project-local setup / template / extension ==="

FAILED=0

# Resolve stock templates for the config merge (dev binary may not have a release zip).
REPO_ROOT="$(cd "$SCRIPT_DIR/../../.." && pwd)"
if [[ ! -d "$REPO_ROOT/templates" ]]; then
  echo "ERROR: stock templates not found at $REPO_ROOT/templates" >&2
  exit 1
fi
export CB_TEMPLATES_PATH="$REPO_ROOT/templates"

# Ensure the hand-placed setup stays executable (git may drop the bit on some clones).
chmod +x .booth/setups/local-hand--setup.sh
chmod +x .booth/templates/project/localgadget/setups/localgadget--setup.sh

# Drop leftovers from a previous run so config starts from fixtures only
# (hand-placed local-hand setup + templates/). Generated Boothfile / config /
# template-emitted setups are recreated below.
rm -f .booth/Boothfile .booth/config.toml .booth/.generated
rm -f .booth/setups/localgadget--setup.sh .booth/setups/localgadget-widget--setup.sh
rm -rf .booth/.tmp

# --- Step 1: Generate .booth from project-local template + extension -------------
# Overwrite any prior generated Boothfile/config from earlier runs.
CONFIG_LOG="$(mktemp)"
if ! run_coding_booth config --no-tui --overwrite --select "localgadget+widget" \
  >"$CONFIG_LOG" 2>&1; then
  echo "ERROR: booth config failed" >&2
  cat "$CONFIG_LOG" >&2
  rm -f "$CONFIG_LOG"
  exit 1
fi
# Surface override warnings if any (should be none for these unique names).
grep -E '^Warning: project template' "$CONFIG_LOG" || true

# --- Assertions on generated Boothfile (template + extension selectable) ---------

if grep -qF 'CB_DETECT_TEMPLATE_v1' .booth/Boothfile \
  && grep -qE '^setup localgadget$' .booth/Boothfile; then
  print_test_result "true" "$0" "1" "Local template contributed Boothfile marker + setup localgadget"
else
  print_test_result "false" "$0" "1" "Local template should emit CB_DETECT_TEMPLATE_v1 and setup localgadget"
  echo "  Boothfile:"
  cat .booth/Boothfile | sed 's/^/    /'
  FAILED=$((FAILED + 1))
fi

if grep -qF 'CB_DETECT_EXTENSION_v1' .booth/Boothfile \
  && grep -qE '^setup localgadget-widget$' .booth/Boothfile; then
  print_test_result "true" "$0" "2" "Local extension contributed Boothfile marker + setup localgadget-widget"
else
  print_test_result "false" "$0" "2" "Local extension should emit CB_DETECT_EXTENSION_v1 and setup localgadget-widget"
  echo "  Boothfile:"
  cat .booth/Boothfile | sed 's/^/    /'
  FAILED=$((FAILED + 1))
fi

if grep -qE '^setup local-hand$' .booth/Boothfile \
  && [[ -f .booth/setups/local-hand--setup.sh ]]; then
  print_test_result "true" "$0" "3" "Local hand-placed setup is referenced and present under .booth/setups/"
else
  print_test_result "false" "$0" "3" "setup local-hand should be in Boothfile and .booth/setups/local-hand--setup.sh should exist"
  FAILED=$((FAILED + 1))
fi

# Template/extension setup scripts should have been written by config.
if [[ -f .booth/setups/localgadget--setup.sh ]] \
  && [[ -f .booth/setups/localgadget-widget--setup.sh ]]; then
  print_test_result "true" "$0" "4" "Config wrote template + extension setup scripts into .booth/setups/"
else
  print_test_result "false" "$0" "4" "Expected localgadget and localgadget-widget setup scripts after config"
  ls -la .booth/setups/ 2>/dev/null | sed 's/^/    /' || true
  FAILED=$((FAILED + 1))
fi

# --- Step 2: Build + run — each layer must leave its marker inside the image -----
# Pin a published base image: a local rc binary tags BOOTH_VERSION_TAG as
# e.g. 0.64.0--rc1, which is not always on Docker Hub. Prefer a concrete tag
# that exists locally, else "latest".
BOOTH_IMG_VERSION="latest"
if docker image inspect "nawaman/codingbooth:base-0.64.0" >/dev/null 2>&1; then
  BOOTH_IMG_VERSION="0.64.0"
elif docker image inspect "nawaman/codingbooth:base-latest" >/dev/null 2>&1; then
  BOOTH_IMG_VERSION="latest"
fi

CB_STDERR_LOG="${CONFIG_LOG}"
# Shorthand: every run uses the same version + silence-build.
# Usage: booth_run "<pipeline>" <cmd...>
booth_run() {
  local pipeline="$1"
  shift
  capture_codingbooth "$pipeline" --version "$BOOTH_IMG_VERSION" --silence-build -- "$@"
}

T_MARK=$(booth_run "tr -d '\r\n'" cat /tmp/cb-local-template-marker.txt) || true
if [[ "$T_MARK" == "CB_DETECT_TEMPLATE_v1" ]]; then
  print_test_result "true" "$0" "5" "Template setup ran (marker CB_DETECT_TEMPLATE_v1)"
else
  print_test_result "false" "$0" "5" "Template setup should write CB_DETECT_TEMPLATE_v1 to /tmp/cb-local-template-marker.txt"
  echo "  Actual: '$T_MARK'"
  tail -40 "$CONFIG_LOG" 2>/dev/null | sed 's/^/    /' || true
  FAILED=$((FAILED + 1))
fi

E_MARK=$(booth_run "tr -d '\r\n'" cat /tmp/cb-local-extension-marker.txt) || true
if [[ "$E_MARK" == "CB_DETECT_EXTENSION_v1" ]]; then
  print_test_result "true" "$0" "6" "Extension setup ran (marker CB_DETECT_EXTENSION_v1)"
else
  print_test_result "false" "$0" "6" "Extension setup should write CB_DETECT_EXTENSION_v1 to /tmp/cb-local-extension-marker.txt"
  echo "  Actual: '$E_MARK'"
  FAILED=$((FAILED + 1))
fi

S_MARK=$(booth_run "tr -d '\r\n'" cat /tmp/cb-local-setup-marker.txt) || true
if [[ "$S_MARK" == "CB_DETECT_SETUP_v1" ]]; then
  print_test_result "true" "$0" "7" "Hand-placed local setup ran (marker CB_DETECT_SETUP_v1)"
else
  print_test_result "false" "$0" "7" "Local setup should write CB_DETECT_SETUP_v1 to /tmp/cb-local-setup-marker.txt"
  echo "  Actual: '$S_MARK'"
  FAILED=$((FAILED + 1))
fi

# Commands installed by each setup
T_CMD=$(booth_run "tr -d '\r\n'" cb-local-template) || true
E_CMD=$(booth_run "tr -d '\r\n'" cb-local-extension) || true
S_CMD=$(booth_run "tr -d '\r\n'" cb-local-setup) || true

if [[ "$T_CMD" == "CB_DETECT_TEMPLATE_v1" \
   && "$E_CMD" == "CB_DETECT_EXTENSION_v1" \
   && "$S_CMD" == "CB_DETECT_SETUP_v1" ]]; then
  print_test_result "true" "$0" "8" "All three layer commands report their markers"
else
  print_test_result "false" "$0" "8" "cb-local-{template,extension,setup} should each print their marker"
  echo "  template='$T_CMD' extension='$E_CMD' setup='$S_CMD'"
  FAILED=$((FAILED + 1))
fi

# Profile env from each layer (login shell)
PROF=$(booth_run "tr -d '\r'" \
  'bash -lc "echo T=\$CB_LOCAL_TEMPLATE_MARKER E=\$CB_LOCAL_EXTENSION_MARKER S=\$CB_LOCAL_SETUP_MARKER"') || true
if echo "$PROF" | grep -q 'T=CB_DETECT_TEMPLATE_v1' \
  && echo "$PROF" | grep -q 'E=CB_DETECT_EXTENSION_v1' \
  && echo "$PROF" | grep -q 'S=CB_DETECT_SETUP_v1'; then
  print_test_result "true" "$0" "9" "Profile scripts export all three layer markers"
else
  print_test_result "false" "$0" "9" "Login shell should export CB_LOCAL_*_MARKER for each layer"
  echo "  Actual: '$PROF'"
  FAILED=$((FAILED + 1))
fi

rm -f "$CONFIG_LOG"
exit $FAILED
