# NOTE: This template has not been tested -- no time (sorry). Please report success or failure. :-p
display-name = "SSH Config"
display-disc = "SSH key and config from host for remote access"
display-detail = "Mounts host SSH keys and configuration into the container for remote server access and Git over SSH."
display-order = 34
tags = [
    "ssh",
    "credential",
    "git"
]

run-args = [
    "-v", "~/.ssh:/etc/cb-home-seed/.ssh:ro"
]
