run := if env("BOOTH_CONTAINER_NAME", "") == "" { "./booth exec --run --" } else { "" }

[private]
default:
    @just --list

# Serve www/ on :8080
start:
    {{run}} ./start-server.sh

# Stop the HTTP server
stop:
    {{run}} ./stop-server.sh
