# Configured by: booth config --no-tui --overwrite --variant notebook --select python+pip-config+vscode-ext/notebook/bash-nb-kernel/aws-cli+credential/claude-code+credential+settings-cache/antigravity+credential

variant = "notebook"

run-args = [
    "-e", "PYTHONDONTWRITEBYTECODE=1",
    "-v", "~/.config/pip:/etc/cb-home-seed/.config/pip:ro",
    "-v", "~/.aws:/etc/cb-home-seed/.aws:ro",
    "-v", "~/.claude.json:/etc/cb-home-seed/.claude.json:ro",
    "-v", "~/.claude/.credentials.json:/etc/cb-home/.claude/.credentials.json:ro",
    "-v", "~/.config/Antigravity:/etc/cb-home-seed/.config/Antigravity:ro",
    "-v", "~/Library/Application Support/Antigravity:/etc/cb-home-seed/.config/Antigravity:ro",
    "-v", "~/AppData/Roaming/Antigravity:/etc/cb-home-seed/.config/Antigravity:ro",
    "-v", "~/.antigravity:/etc/cb-home-seed/.antigravity:ro"
]
