# Configured by: booth config --no-tui --overwrite --variant kde --expose +-7000:3000 --expose +-4827:5173 --select nodejs:20/bun:1.3.6/deno:2.6.5/webstorm/claude-code/antigravity

variant = "kde"

run-args = [
    "-v", "~/.npmrc:/etc/cb-home-seed/.npmrc:ro",
    "-v", "~/.claude.json:/etc/cb-home-seed/.claude.json:ro",
    "-v", "~/.claude/.credentials.json:/etc/cb-home/.claude/.credentials.json:ro",
    "-v", "~/.config/Antigravity:/etc/cb-home-seed/.config/Antigravity:ro",
    "-v", "~/Library/Application Support/Antigravity:/etc/cb-home-seed/.config/Antigravity:ro",
    "-v", "~/AppData/Roaming/Antigravity:/etc/cb-home-seed/.config/Antigravity:ro",
    "-v", "~/.antigravity:/etc/cb-home-seed/.antigravity:ro",
    "--publish", "+-7000:3000",
    "--publish", "+-4827:5173"
]
