display-name = "SQLite"
primary = true
display-disc = "SQLite embedded database"
display-order = 10
tags = [
    "database",
    "sqlite",
    "embedded"
]

[segments]
Boothfile = """
setup sqlite
"""
