run := if env("BOOTH_CONTAINER_NAME", "") == "" { "./booth exec --run --" } else { "" }

[private]
default:
    @just --list

# Build the tripboard static binary
build:
    {{run}} ./build.sh

# Build if needed and serve on :8090
start:
    {{run}} ./start.sh
