[private]
default:
    @just --list

# Create the KinD cluster
start:
    ./start-cluster.sh

# Deploy the sample app
deploy:
    ./deploy-app.sh

# Check cluster status (`just check down`)
check expect="up":
    ./check-cluster.sh --expect={{ expect }}

# Delete the cluster
stop:
    ./stop-cluster.sh
