display-name = "Jupyter Notebook"
display-disc = "JupyterLab notebook server"
display-order = 24
requires = ["python"]
tags = [
    "jupyter",
    "notebook",
    "python"
]

[segments]
"Boothfile--60" = """
setup notebook
"""
