#!/bin/bash
set -e
# Generated by: booth init new /home/nawa/dev/git/CodingBooth/prj--test46-init-excalidraw --select excalidraw:889+expose+autostart
# Adjust with : booth init adjust --select excalidraw:889+expose+autostart

# Auto-start Excalidraw in background
PORT=${EXCALIDRAW_PORT}
LOG_FILE="/tmp/excalidraw.log"

nohup serve -s --no-clipboard /opt/excalidraw -l "$PORT" > "$LOG_FILE" 2>&1 &

echo "Excalidraw started on port $PORT (PID $!, log: $LOG_FILE)"
