# Configured by: booth config --no-tui --overwrite --variant xfce --select java+maven+vscode-ext+kernel/python/notebook/idea+lombok/eclipse/jetbrains-plugin-pkg

variant = "xfce"

run-args = [
    "-e", "PYTHONDONTWRITEBYTECODE=1",
    "-v", "~/.config/pip:/etc/cb-home-seed/.config/pip:ro"
]
