# NOTE: This template has not been tested -- no time (sorry). Please report success or failure. :-p
display-name = "Zig VS Code Extension"
display-disc = "Zig language support for VS Code"
display-order = 1
auto-select = true
tags = [
    "zig",
    "ide",
    "vscode",
]

[segments]
"Boothfile--65" = """
setup zig-code-extension
"""
