run := if env("BOOTH_CONTAINER_NAME", "") == "" { "./booth exec --run --" } else { "" }

[private]
default:
    @just --list

# Cross-compile treemoji into ./bin/
build:
    {{run}} ./build.sh

# Run treemoji (builds first if needed)
run *args:
    {{run}} ./run-treemoji.sh {{ args }}

# Run Go unit tests
test:
    {{run}} ./run-go-test.sh
