run := if env("BOOTH_CONTAINER_NAME", "") == "" { "./booth exec --run --" } else { "" }

[private]
default:
    @just --list

# Compile the console app
build:
    {{run}} dotnet build --project .

# Build and run
run:
    {{run}} ./run-csharp.sh
