# syntax=docker/dockerfile:1.7
# Empty Example Dockerfile

ARG BOOTH_VARIANT_TAG=base
ARG BOOTH_VERSION_TAG=latest

FROM nawaman/codingbooth:${BOOTH_VARIANT_TAG}-${BOOTH_VERSION_TAG}

ARG BOOTH_VARIANT_TAG=base
ARG BOOTH_VERSION_TAG=latest


#== Setup ==

# RUN command to setup things (see setup scripts in /opt/codingbooth/setups)

# RUN jdk--setup.sh 25