# syntax=docker/dockerfile:1.7
# Empty Example Dockerfile

ARG CB_VARIANT_TAG=base
ARG CB_VERSION_TAG=latest

FROM nawaman/codingbooth:${CB_VARIANT_TAG}-${CB_VERSION_TAG}

ARG CB_VARIANT_TAG=base
ARG CB_VERSION_TAG=latest


#== Setup ==

# RUN command to setup things (see setup scripts in /opt/codingbooth/setups)

# RUN jdk--setup.sh 25