# Configured by: booth config --no-tui --overwrite --variant xfce --select python+vscode-ext+kernel/notebook/xfce/claude-code

variant = "xfce"

run-args = [
    "-e", "PYTHONDONTWRITEBYTECODE=1",
    "-v", "~/.config/pip:/etc/cb-home-seed/.config/pip:ro",
    "-v", "~/Library/Application Support/pip:/etc/cb-home-seed/.config/pip:ro",
    "-v", "~/AppData/Roaming/pip:/etc/cb-home-seed/.config/pip:ro",
    "-v", "~/.claude.json:/etc/cb-home-seed/.claude.json:ro",
    "-v", "~/.claude/.credentials.json:/etc/cb-home/.claude/.credentials.json:ro"
]
