display-name = "AWS Credentials"
display-disc = "Mount host AWS CLI credentials (shared with AWS CLI)"
auto-select = true
tags = ["aws", "credential"]

run-args = [
    "-v", "~/.aws:/etc/cb-home-seed/.aws:ro"
]
