# Configured by: booth config --no-tui --overwrite --variant base --select firebase+credential

variant = "base"

run-args = ["-v", "~/.config/configstore/firebase-tools.json:/etc/cb-home-seed/.config/configstore/firebase-tools.json:ro"]
