run := if env("BOOTH_CONTAINER_NAME", "") == "" { "./booth exec --run --" } else { "" }

[private]
default:
    @just --list

# Compile the web target
build:
    {{run}} bash -c 'cd booth_counter && flutter build web --release'

# Serve on :8080 (open /proxy/8080/ on the booth)
run:
    {{run}} bash -c 'cd booth_counter && flutter run -d web-server --web-port 8080 --web-hostname 0.0.0.0'

# Run widget tests
test:
    {{run}} bash -c 'cd booth_counter && flutter test'
