# Configured by: booth config --no-tui --overwrite --variant xfce --port 50411 --set common-args=--platform --set common-args=${CB_ANDROID_PLATFORM:-linux/amd64} --select java:17/android-sdk+emulator+kvm

variant = "xfce"
port = "50411"

run-args = ["--device", "/dev/kvm"]

common-args = ["--platform", "${CB_ANDROID_PLATFORM:-linux/amd64}"]
