# NOTE: This template has not been tested -- no time (sorry). Please report success or failure. :-p
display-name = "Antigravity Credentials"
display-disc = "Mount host Antigravity credentials"
auto-select = true
tags = ["antigravity", "credential"]

run-args = [
    "-v", "~/.config/Antigravity:/etc/cb-home-seed/.config/Antigravity:ro",
    "-v", "~/.antigravity:/etc/cb-home-seed/.antigravity:ro"
]
