# NOTE: This template has not been tested -- no time (sorry). Please report success or failure. :-p
display-name = "GCloud Credentials"
display-disc = "Mount host Google Cloud SDK credentials"
display-order = 90
auto-select = true
tags = ["credential", "gcloud"]

run-args = [
    # Google Cloud credentials (home-seeding: gcloud may refresh tokens)
    "-v", "~/.config/gcloud:/etc/cb-home-seed/.config/gcloud:ro",
]
