display-name = "Google Cloud SDK"
display-disc = "Google Cloud SDK for GCP service management"
display-detail = "Installs the Google Cloud SDK (gcloud) for managing Google Cloud Platform resources and services."
display-order = 52
tags = [
    "gcloud",
    "cloud",
    "cli"
]

[params.GCLOUD_VERSION]
default = "latest"
suggests = ["latest"]

[segments]
Boothfile = """
setup gcloud --version ${GCLOUD_VERSION}
"""
