display-name = "Python Notebook Kernel"
display-disc = "ipykernel for Python"
display-order = 5
auto-select = false
requires = ["notebook"]
tags = [
    "python",
    "kernel",
    "notebook"
]

[segments]
"Boothfile--70" = """
setup python-nb-kernel
"""
