// Copyright 2025-2026 : Nawa Manusitthipol
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.

package catalog

import (
	"fmt"
	"regexp"
	"strconv"
	"strings"
)

const manifestHeader = "# CodingBooth catalog manifest — generated by build/gen-catalog-manifest.sh; do not edit.\n" +
	"# See docs/CATALOG_VERSIONING.md.\n" +
	"kind\tname\tcb-version\tsha256\tpath\n"

// Format renders items as the manifest TSV. Items are expected to be sorted.
func Format(items []Item) string {
	var sb strings.Builder
	sb.WriteString(manifestHeader)
	for _, it := range items {
		fmt.Fprintf(&sb, "%s\t%s\t%s\t%s\t%s\n", it.Kind, it.Name, it.Version, it.SHA256, it.Path)
	}
	return sb.String()
}

// Parse reads a manifest written by Format.
func Parse(text string) ([]Item, error) {
	var items []Item
	for n, line := range strings.Split(text, "\n") {
		if line == "" || strings.HasPrefix(line, "#") || strings.HasPrefix(line, "kind\t") {
			continue
		}
		f := strings.Split(line, "\t")
		if len(f) != 5 {
			return nil, fmt.Errorf("manifest line %d: want 5 fields, got %d", n+1, len(f))
		}
		items = append(items, Item{Kind: f[0], Name: f[1], Version: f[2], SHA256: f[3], Path: f[4]})
	}
	return items, nil
}

// Semver is a MAJOR.MINOR.PATCH version. Pre-release and build suffixes are
// deliberately not accepted: a catalog item is either released or it is not.
type Semver struct{ Major, Minor, Patch int }

var semverRe = regexp.MustCompile(`^(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)$`)

// ParseSemver parses "1.2.3".
func ParseSemver(s string) (Semver, error) {
	m := semverRe.FindStringSubmatch(s)
	if m == nil {
		return Semver{}, fmt.Errorf("not a MAJOR.MINOR.PATCH version: %q", s)
	}
	maj, _ := strconv.Atoi(m[1])
	min, _ := strconv.Atoi(m[2])
	pat, _ := strconv.Atoi(m[3])
	return Semver{maj, min, pat}, nil
}

// Compare returns -1, 0 or 1.
func (v Semver) Compare(o Semver) int {
	for _, d := range [][2]int{{v.Major, o.Major}, {v.Minor, o.Minor}, {v.Patch, o.Patch}} {
		if d[0] < d[1] {
			return -1
		}
		if d[0] > d[1] {
			return 1
		}
	}
	return 0
}

func (v Semver) String() string { return fmt.Sprintf("%d.%d.%d", v.Major, v.Minor, v.Patch) }

// Breaking reports whether going from v to next is a breaking bump: a new major
// from 1.0.0 on, or a new minor below it (semver's 0.x rule).
func (v Semver) Breaking(next Semver) bool {
	if v.Major == 0 {
		return next.Major > 0 || next.Minor > v.Minor
	}
	return next.Major > v.Major
}

// Level is how serious a Finding is.
type Level string

const (
	Fail Level = "FAIL"
	Warn Level = "WARN"
	Info Level = "INFO"
)

// Finding is one line of a Check report.
type Finding struct {
	Level Level
	Item  Item
	Msg   string
}

func (f Finding) String() string {
	return fmt.Sprintf("%-4s  %-9s %-34s %s", f.Level, f.Item.Kind, f.Item.Name, f.Msg)
}

// ParamLookup returns the declaration-ordered params of a template or extension
// item, or ok=false when they cannot be read (the item has no such file there).
type ParamLookup func(it Item) (params []string, ok bool)

// Check compares the current items against a baseline (nil when there is none:
// the first versioned release) and returns its findings.
//
//   - every current item must declare a valid cb-version;
//   - a changed hash with an unchanged version fails;
//   - a version lower than the baseline fails;
//   - a changed version with an unchanged hash warns;
//   - a template or extension whose params were removed or reordered fails
//     unless the bump is breaking (new major; new minor below 1.0.0) —
//     positional selection (`java:21,corretto`) depends on that order.
//
// baseParams and curParams may be nil, which skips the param check.
func Check(base, cur []Item, baseParams, curParams ParamLookup) []Finding {
	var out []Finding
	baseBy := map[string]Item{}
	for _, b := range base {
		baseBy[b.Key()] = b
	}
	seen := map[string]bool{}
	for _, c := range cur {
		seen[c.Key()] = true
		cv, err := ParseSemver(c.Version)
		if err != nil {
			msg := "no cb-version (" + c.Path + ")"
			if c.Version != "" {
				msg = fmt.Sprintf("invalid cb-version %q (%s)", c.Version, c.Path)
			}
			out = append(out, Finding{Fail, c, msg})
			continue
		}
		if base == nil {
			continue
		}
		b, ok := baseBy[c.Key()]
		if !ok {
			out = append(out, Finding{Info, c, "new at " + cv.String()})
			continue
		}
		bv, err := ParseSemver(b.Version)
		if err != nil {
			// Baseline predates versioning for this item; nothing to compare.
			continue
		}
		switch cmp := cv.Compare(bv); {
		case cmp < 0:
			out = append(out, Finding{Fail, c, fmt.Sprintf("version went down: %s → %s", bv, cv)})
			continue
		case cmp == 0 && c.SHA256 != b.SHA256:
			out = append(out, Finding{Fail, c, fmt.Sprintf("changed since the baseline but still %s — bump cb-version (%s)", cv, c.Path)})
			continue
		case cmp > 0 && c.SHA256 == b.SHA256:
			out = append(out, Finding{Warn, c, fmt.Sprintf("bumped %s → %s with no change", bv, cv)})
			continue
		case cmp == 0:
			continue
		}
		// Version went up with a change: check the param contract.
		if (c.Kind == KindTemplate || c.Kind == KindExtension) && baseParams != nil && curParams != nil && !bv.Breaking(cv) {
			bp, ok1 := baseParams(b)
			cp, ok2 := curParams(c)
			if ok1 && ok2 && !IsPrefix(bp, cp) {
				out = append(out, Finding{Fail, c, fmt.Sprintf(
					"params removed or reordered (%s → %s) needs a breaking bump, not %s → %s",
					strings.Join(bp, ","), strings.Join(cp, ","), bv, cv)})
				continue
			}
		}
		out = append(out, Finding{Info, c, fmt.Sprintf("%s → %s", bv, cv)})
	}
	for _, b := range base {
		if !seen[b.Key()] {
			out = append(out, Finding{Info, b, "removed (was " + b.Version + ")"})
		}
	}
	return out
}

// IsPrefix reports whether old is a prefix of cur: params may only be appended.
func IsPrefix(old, cur []string) bool {
	if len(old) > len(cur) {
		return false
	}
	for i := range old {
		if old[i] != cur[i] {
			return false
		}
	}
	return true
}

// HasFail reports whether any finding is a failure.
func HasFail(fs []Finding) bool {
	for _, f := range fs {
		if f.Level == Fail {
			return true
		}
	}
	return false
}
