# NOTE: This template has not been tested -- no time (sorry). Please report success or failure. :-p
display-name = "Neovim Config"
display-disc = "Mount host Neovim configuration files"
auto-select = true
tags = [
    "neovim",
    "config"
]

run-args = [
    "-v", "~/.config/nvim:/etc/cb-home-seed/.config/nvim:ro"
]
