run := if env("BOOTH_CONTAINER_NAME", "") == "" { "./booth exec --run --" } else { "" }

[private]
default:
    @just --list

# Production build
build:
    {{run}} bash -c 'npm install && npm run build'

# Angular dev server on :4200
run:
    {{run}} bash -c 'npm install && npm start'
