run := if env("BOOTH_CONTAINER_NAME", "") == "" { "./booth exec --run --" } else { "" }

[private]
default:
    @just --list

# Production build
build:
    {{run}} bash -c 'npm install && npm run build'

# Next.js dev server on :3000
run:
    {{run}} bash -c 'npm install && npm run dev'
