# NOTE: This template has not been tested -- no time (sorry). Please report success or failure. :-p
display-name = "Cargo Cache"
display-disc = "Persist ~/.cargo registry cache across container restarts"
auto-select = true
tags = ["rust", "cargo", "cache"]

run-args = [
    "-v", "$HOME/.cargo/registry:/home/coder/.cargo/registry"
]
