# NOTE: This template has not been tested -- no time (sorry). Please report success or failure. :-p
display-name = "Cargo Credentials"
display-disc = "Mount host Rust/Cargo credentials"
auto-select = true
tags = ["rust", "cargo", "credential"]

run-args = [
    "-v", "~/.cargo/credentials.toml:/etc/cb-home-seed/.cargo/credentials.toml:ro"
]
