display-name = "Rust Notebook Kernel"
display-disc = "Rust Jupyter notebook kernel (evcxr)"
display-order = 5
auto-select = false
requires = ["notebook"]
tags = [
    "rust",
    "kernel",
    "notebook"
]

[segments]
"Boothfile--70" = """
setup rust-nb-kernel
"""
