display-name = "Rust VS Code Extension"
display-disc = "rust-analyzer for VS Code"
display-order = 1
auto-select = true
tags = [
    "rust",
    "ide",
    "vscode",
]

[segments]
"Boothfile--65" = """
setup rust-code-extension
"""
