# Configured by: booth config --no-tui --overwrite --variant xfce --select python~vscode-ext/thonny/apt-pkg:tk,xvfb/nodejs~vscode-ext/logo+autostart+expose

variant = "xfce"

run-args = [
    "-e", "PYTHONDONTWRITEBYTECODE=1",
    "-v", "~/.config/pip:/etc/cb-home-seed/.config/pip:ro",
    "-v", "~/Library/Application Support/pip:/etc/cb-home-seed/.config/pip:ro",
    "-v", "~/AppData/Roaming/pip:/etc/cb-home-seed/.config/pip:ro",
    "-v", "~/.npmrc:/etc/cb-home-seed/.npmrc:ro",
    "-p", "18610:18610"
]
