display-name = "R Notebook Kernel"
display-disc = "R Jupyter notebook kernel (IRkernel)"
display-order = 5
auto-select = false
requires = ["notebook"]
tags = [
    "r",
    "kernel",
    "notebook"
]

[segments]
"Boothfile--70" = """
setup r-nb-kernel
"""
