# NOTE: This template has not been tested -- no time (sorry). Please report success or failure. :-p
display-name = "R VS Code Extension"
display-disc = "R language support for VS Code"
display-order = 1
auto-select = true
tags = [
    "r",
    "ide",
    "vscode",
]

[segments]
"Boothfile--65" = """
setup r-code-extension
"""
