display-name = "Maven Local Repository"
display-disc = "Mount host Maven repository cache (.m2)"
display-order = 9
auto-select = false
tags = [
    "java",
    "maven",
    "gradle",
    "cache"
]

run-args = [
    "-v", "$HOME/.m2:/home/coder/.m2"
]
