display-name = "Maven"
display-disc = "Apache Maven build tool for Java projects"
display-order = 10
auto-select = false
tags = [
    "build",
    "maven"
]

[params.MAVEN_VERSION]
default = "3.9.12"
suggests = [
    "3.9.12", "3.9",
    "4.0.0-rc-5",
]

[segments]
Boothfile = """
setup mvn ${MAVEN_VERSION}
"""
