display-name = "Java"
display-disc = "JDK with build tools"
display-order = 30
tags = [
    "java",
    "jvm",
    "backend",
    "awesome"
]

[params.JAVA_VERSION]
default = "21"
suggests = [
    "25",
    "21",
    "17",
    "11",
    "8"
]

[params.JAVA_VENDOR]
default = "temurin"
suggests = [
    "temurin",
    "corretto",
    "openjdk"
]