run := if env("BOOTH_CONTAINER_NAME", "") == "" { "./booth exec --run --" } else { "" }

[private]
default:
    @just --list

# Package the Vaadin app
build:
    {{run}} mvn -q package

# Run the UI on :8080
run:
    {{run}} mvn spring-boot:run
