display-name = "Free Pascal"
display-disc = "Free Pascal compiler and development tools"
display-detail = "Installs the Free Pascal compiler for Object Pascal development."
display-order = 78
tags = [
    "pascal",
    "compiled"
]

[params.FPC_VERSION]
default = "latest"
suggests = ["latest"]

[segments]
Boothfile = """
setup fpc --version ${FPC_VERSION}
"""
