display-name = "Clojure"
display-disc = "Clojure language"
display-order = 36
tags = [
    "clojure",
    "jvm",
    "functional"
]
requires = ["java"]

[segments]
"Boothfile--60" = """
setup clojure
"""
