# NOTE: This template has not been tested -- no time (sorry). Please report success or failure. :-p
display-name = "Clojure VS Code Extension"
display-disc = "Clojure language support extension for VS Code"
display-order = 1
auto-select = true
tags = [
    "clojure",
    "ide",
    "vscode",
]

[segments]
"Boothfile--65" = """
setup clojure-code-extension
"""
