# NOTE: This template has not been tested -- no time (sorry). Please report success or failure. :-p
display-name = "Git Credentials"
display-disc = "Mount ~/.gitconfig from host (read-only home-seeding)"
display-order = 31
tags = [
    "git",
    "credential"
]

run-args = [
    "-v", "~/.gitconfig:/etc/cb-home-seed/.gitconfig:ro"
]
