# Configured by: booth config --no-tui --overwrite --expose +-1920:80 --select php~vscode-ext/mysql/nginx+php-fpm/lemp-init


run-args = [
    "-v", "booth-mysqldata:/var/lib/mysql",
    "--publish", "+-1920:80"
]
