# Configured by: booth config --no-tui --overwrite --variant xfce --port NEXT:25000 --select google-chrome+bookmarks-shared+settings-shared+extensions-shared+managed-policies/firefox+bookmarks-shared+settings-shared+extensions-shared+managed-policies

variant = "xfce"
port = "NEXT:25000"

shared-dirs = [
    "home/coder/.chrome-data/Default",
    "home/coder/.chrome-data/Default/Extensions",
    "home/coder/.mozilla/firefox"
]
