display-name = "Docker Compose"
display-disc = "Docker Compose plugin for multi-container apps"
display-detail = "Installs the Docker Compose plugin for defining and running multi-container Docker applications."
display-order = 64
tags = [
    "docker",
    "compose"
]

[segments]
Boothfile = """
setup docker-compose
"""
