// Copyright 2025-2026 : Nawa Manusitthipol
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.

package main

import (
	"fmt"
	"io"
	"os"
	"path/filepath"
	"reflect"
	"sort"
	"strings"

	"github.com/BurntSushi/toml"
	"github.com/nawaman/codingbooth/src/pkg/appctx"
	"github.com/nawaman/codingbooth/src/pkg/boothinit/cache"
	"github.com/nawaman/codingbooth/src/pkg/boothinit/output"
	"github.com/nawaman/codingbooth/src/pkg/boothinit/selection"
	tmpl "github.com/nawaman/codingbooth/src/pkg/boothinit/template"
)

// Adopting an edited booth
//
// A booth config generated and then edited by hand fails its fingerprint (see
// output.Drifted), and until now that alone made it "hand-written": the TUI opened
// behind a warning, and a save could only replace the edit or write beside it —
// even when the edit was a `timezone` line booth config could have written itself.
//
// adoptEdits reads such a booth back instead:
//
//  1. regenerate what the recorded header produces — the baseline;
//  2. lift every difference between that and the files on disk into flags
//     (a changed key becomes --set, a run-args entry --env/--expose/--mount, an
//     edited `arg` pin the selection's param);
//  3. regenerate from the lifted flags, and compare with the files on disk,
//     ignoring only comments and whitespace.
//
// Only an exact match is adopted, so nothing is ever guessed: a save regenerates
// the same directives and settings the user wrote. Anything else — a `run` line no
// template produces, entries in an order booth config does not write — falls back
// to the hand-written handling, with the reasons spelled out.
//
// Comments cannot become flags, so they do not survive a save; the lost list says
// which ones, for the caller to warn about before writing. Viewing writes nothing.

// adoptResult is what adoptEdits found.
type adoptResult struct {
	// attempted is false when there was nothing to read back from: no
	// "# Configured by:" header, so the files were never generated by booth config.
	attempted bool
	adopted   bool

	// flags is the baseline with the edits lifted in — used instead of the header
	// when adopted.
	flags initFlags

	// lost lists the comments a save would remove.
	lost []lostComment

	// reasons says why the edits could not be read back, when not adopted.
	reasons []string
}

type lostComment struct {
	file string
	output.Comment
}

// runArgFlagForms maps each run-args flag booth config can lift to its long form.
// The short form is what templates write and the long form what the user flags
// write; docker reads both alike, so an entry added by hand in either form lifts.
var runArgFlagForms = map[string]string{
	"-e": "--env", "--env": "--env",
	"-p": "--publish", "--publish": "--publish",
	"-v": "--volume", "--volume": "--volume",
}

// adoptEdits tries to read the edited booth at targetPath back into flags. base is
// the baseline readExistingBooth produced; cli is this run's own flags, which only
// steer where the templates come from.
func adoptEdits(version, targetPath string, base, cli initFlags) adoptResult {
	// A hand-written Boothfile carries no header — that alone is not something to
	// read back, even when config.toml records how the rest was configured.
	if _, found := readConfiguredByHeader(filepath.Join(targetPath, ".booth", "Boothfile")); !found {
		if _, err := os.Stat(filepath.Join(targetPath, ".booth", "Boothfile")); err == nil {
			return adoptResult{}
		}
	}
	if _, _, found := readBoothHeader(targetPath); !found {
		return adoptResult{}
	}
	result := adoptResult{attempted: true}

	// Compiling prints notes and warnings meant for a run the user asked for; this
	// is a check they did not, so it keeps quiet.
	restore := muteStderr()
	defer restore()

	diskConfig := readBoothFile(targetPath, "config.toml")
	diskBoothfile := readBoothFile(targetPath, "Boothfile")

	base.selectDSL = strings.Join(base.selectDSLs, "/")
	if len(base.selectDSLs) > 0 {
		templatesPath, cleanup, err := adoptTemplatesPath(version, targetPath, base, cli)
		defer cleanup()
		if err != nil {
			result.reasons = append(result.reasons, err.Error())
			return result
		}
		base.templatesPath = templatesPath
	}

	expected, err := compileForAdopt(base, targetPath)
	if err != nil {
		result.reasons = append(result.reasons, "the recorded configuration no longer compiles: "+err.Error())
		return result
	}

	lifted, reasons := liftEdits(base, expected, diskConfig, targetPath)
	if len(reasons) > 0 {
		// The Boothfile does not depend on what config.toml failed to lift, so
		// still say what blocks it too — otherwise fixing the reported problems
		// only uncovers the next ones.
		if regenerated, err := compileForAdopt(lifted, targetPath); err == nil {
			regenBoothfile := output.SerializeBoothfile(regenerated.Boothfile, "", "")
			reasons = append(reasons, compareBoothfile(diskBoothfile, regenBoothfile)...)
		}
		result.reasons = reasons
		return result
	}

	regenerated, err := compileForAdopt(lifted, targetPath)
	if err != nil {
		result.reasons = append(result.reasons, "the edits do not compile: "+err.Error())
		return result
	}

	regenConfig := output.SerializeConfigToml(regenerated.Config, "", "")
	regenBoothfile := output.SerializeBoothfile(regenerated.Boothfile, "", "")

	result.reasons = append(result.reasons, compareConfigToml(diskConfig, regenConfig)...)
	result.reasons = append(result.reasons, compareBoothfile(diskBoothfile, regenBoothfile)...)
	if len(result.reasons) > 0 {
		return result
	}

	for _, c := range output.LostComments(output.ConfigTomlComments(diskConfig), output.ConfigTomlComments(regenConfig)) {
		result.lost = append(result.lost, lostComment{file: "config.toml", Comment: c})
	}
	for _, c := range output.LostComments(output.BoothfileComments(diskBoothfile), output.BoothfileComments(regenBoothfile)) {
		result.lost = append(result.lost, lostComment{file: "Boothfile", Comment: c})
	}

	// The templates path was resolved for this check only; the run resolves its own.
	lifted.templatesPath = cli.templatesPath
	lifted.selectDSL = ""
	result.adopted = true
	result.flags = lifted
	return result
}

// adoptTemplatesPath picks the catalog to regenerate against: the release recorded
// in .booth/.generated when there is one — the catalog that actually wrote these
// files — else the one this run would use. Comparing against a newer catalog would
// report its template updates as the user's edits.
func adoptTemplatesPath(version, targetPath string, base, cli initFlags) (string, func(), error) {
	noop := func() {}
	if recorded := output.ReadTemplatesVersion(targetPath); recorded != "" {
		if dir, cleanup, err := cache.ResolveTemplatesDir(recorded); err == nil {
			return dir, cleanup, nil
		}
	}

	if cli.templatesPath != "" {
		return cli.templatesPath, noop, nil
	}
	if cli.version != "" {
		version = cli.version
	} else if base.version != "" {
		version = base.version
	}
	dir, cleanup, err := cache.ResolveTemplatesDir(version)
	if err != nil {
		return "", noop, fmt.Errorf("could not load templates %s to compare against: %v", version, err)
	}
	return dir, cleanup, nil
}

// templatesVersionFor names the release whose catalog a run with these flags
// compiles from — what .booth/.generated records. A local catalog has none.
func templatesVersionFor(flags initFlags, version string) string {
	if flags.templatesPath != "" || len(flags.selectDSLs) == 0 {
		return ""
	}
	if flags.version != "" {
		return flags.version
	}
	return version
}

// compileForAdopt compiles flags the way a reconfigure would, with the booth's own
// APT snapshot — the one the files on disk were written with.
func compileForAdopt(flags initFlags, targetPath string) (*output.BoothOutput, error) {
	var out *output.BoothOutput
	var err error
	if len(flags.selectDSLs) == 0 {
		out, _, err = compileEmptyE(flags)
	} else {
		out, _, err = compileSelectionE(flags, targetPath, readExistingArgs(targetPath))
	}
	if err != nil {
		return nil, err
	}

	id := readExistingAptSnapshot(targetPath)
	if id == "" {
		id = aptSnapshotID()
	}
	applyAptSnapshotID(out, id)
	return out, nil
}

// liftEdits turns the differences between the regenerated baseline (expected) and
// the files on disk into flags. It returns the reasons an edit cannot be lifted;
// whatever it can lift is still proven by the comparison that follows.
func liftEdits(base initFlags, expected *output.BoothOutput, diskConfig, targetPath string) (initFlags, []string) {
	lifted := base
	lifted.sets = append([]string{}, base.sets...)
	var reasons []string

	if diskConfig != "" {
		var disk, gen map[string]interface{}
		if _, err := toml.Decode(diskConfig, &disk); err != nil {
			return lifted, []string{"config.toml is not valid TOML: " + err.Error()}
		}
		if _, err := toml.Decode(output.SerializeConfigToml(expected.Config, "", ""), &gen); err != nil {
			return lifted, []string{"could not read the regenerated config.toml: " + err.Error()}
		}
		reasons = append(reasons, liftRunArgs(&lifted, base, expected, disk)...)
		reasons = append(reasons, liftConfigKeys(&lifted, disk, gen)...)
	}

	liftSelectionParams(&lifted, targetPath)
	return lifted, reasons
}

// liftRunArgs rebuilds the user's --expose/--env/--mount lists from the run-args on
// disk: every entry that is not one of the selected templates' own becomes the
// user's, in the order it appears. That covers entries added (in either form) and
// entries removed, without diffing the two lists entry by entry.
func liftRunArgs(lifted *initFlags, base initFlags, expected *output.BoothOutput, disk map[string]interface{}) []string {
	diskArgs, ok := stringList(disk["run-args"])
	if !ok {
		return []string{"config.toml `run-args` is not a list of strings"}
	}

	// The templates' own entries: everything the baseline generated, less what the
	// baseline's own user flags added.
	userCfg := &output.ConfigToml{}
	applyExposeFlags(userCfg, base.exposes)
	applyEnvFlags(userCfg, base.envs)
	applyMountFlags(userCfg, base.mounts)
	templateOwned := make(map[string]int)
	for _, pair := range runArgPairs(expected.Config.RunArgs) {
		templateOwned[pair.key()]++
	}
	for _, pair := range runArgPairs(userCfg.RunArgs) {
		if templateOwned[pair.key()] > 0 {
			templateOwned[pair.key()]--
		}
	}

	var reasons []string
	var exposes, envs, mounts []string
	for _, pair := range runArgPairs(diskArgs) {
		if templateOwned[pair.key()] > 0 {
			templateOwned[pair.key()]--
			continue
		}
		switch pair.canonicalFlag() {
		case "--env":
			envs = append(envs, pair.value)
		case "--publish":
			exposes = append(exposes, reverseExposeMapping(pair.value))
		case "--volume":
			mounts = append(mounts, pair.value)
		default:
			reasons = append(reasons, fmt.Sprintf("config.toml run-args `%s` has no booth config flag", pair))
		}
	}

	var missing []string
	for key, count := range templateOwned {
		for ; count > 0; count-- {
			missing = append(missing, key)
		}
	}
	sort.Strings(missing)
	for _, key := range missing {
		reasons = append(reasons, fmt.Sprintf("config.toml run-args `%s` comes from a selected template and was removed", key))
	}

	lifted.exposes, lifted.envs, lifted.mounts = exposes, envs, mounts
	return reasons
}

// liftConfigKeys lifts every top-level config.toml key whose value on disk differs
// from the baseline: port/variant/cmds onto their own flags, anything else as
// --set. The list keys that are not flags (build-args, cache-*, shared-*) are left
// to the comparison — cache and shared lists are already read back from disk.
func liftConfigKeys(lifted *initFlags, disk, gen map[string]interface{}) []string {
	keys := make(map[string]bool)
	for k := range disk {
		keys[k] = true
	}
	for k := range gen {
		keys[k] = true
	}
	sorted := make([]string, 0, len(keys))
	for k := range keys {
		sorted = append(sorted, k)
	}
	sort.Strings(sorted)

	schema := appctx.ConfigKeys()
	var reasons []string
	for _, key := range sorted {
		diskValue, onDisk := disk[key]
		if reflect.DeepEqual(diskValue, gen[key]) {
			continue
		}

		switch key {
		case "run-args", "build-args", "cache-files", "cache-dirs", "shared-files", "shared-dirs":
			continue
		case "port":
			lifted.port = scalarString(diskValue)
			continue
		case "variant":
			lifted.variant = scalarString(diskValue)
			continue
		case "cmds":
			cmds, ok := stringList(diskValue)
			if !ok {
				reasons = append(reasons, "config.toml `cmds` is not a list of strings")
				continue
			}
			lifted.cmds = cmds
			continue
		}

		lifted.sets = dropSetsForKey(lifted.sets, key)
		if !onDisk {
			continue
		}
		spec, known := schema[key]
		if !known || !spec.Read {
			reasons = append(reasons, fmt.Sprintf("config.toml `%s` is not a setting booth reads from config.toml", key))
			continue
		}
		sets, err := setsFromTOML(key, diskValue)
		if err != nil {
			reasons = append(reasons, "config.toml "+err.Error())
			continue
		}
		lifted.sets = append(lifted.sets, sets...)
	}

	if len(reasons) == 0 {
		if _, err := parseSetOverrides(lifted.sets); err != nil {
			reasons = append(reasons, "config.toml: "+err.Error())
		}
	}
	return reasons
}

// liftSelectionParams moves an `arg` pin edited by hand into the selection, where
// the selection gives that param explicitly — see selection.LiftParams. A selection
// that cannot be read here is left alone; the comparison decides.
func liftSelectionParams(lifted *initFlags, targetPath string) {
	args := readExistingArgs(targetPath)
	if len(args) == 0 || len(lifted.selectDSLs) == 0 {
		return
	}
	text, err := resolveDSLFragments(lifted.selectDSLs, targetPath)
	if err != nil {
		return
	}
	parsed, err := selection.ParseSelectDSL(text)
	if err != nil {
		return
	}
	registry, err := tmpl.LoadMergedRegistry(lifted.templatesPath, targetPath, io.Discard)
	if err != nil {
		return
	}
	if selection.LiftParams(parsed, registry, args) {
		lifted.selectDSLs = []string{selection.SerializeSelection(parsed)}
		lifted.selectDSL = lifted.selectDSLs[0]
	}
}

// compareConfigToml reports how the config.toml on disk differs from the
// regenerated one, compared as TOML: key order, comments and spacing do not count,
// the order of run-args entries does. Short- and long-form flags compare alike.
func compareConfigToml(diskContent, regenContent string) []string {
	if diskContent == "" {
		return nil
	}
	var disk, regen map[string]interface{}
	if _, err := toml.Decode(diskContent, &disk); err != nil {
		return []string{"config.toml is not valid TOML: " + err.Error()}
	}
	if _, err := toml.Decode(regenContent, &regen); err != nil {
		return []string{"could not read the regenerated config.toml: " + err.Error()}
	}
	canonicalizeRunArgs(disk)
	canonicalizeRunArgs(regen)

	keys := make(map[string]bool)
	for k := range disk {
		keys[k] = true
	}
	for k := range regen {
		keys[k] = true
	}
	sorted := make([]string, 0, len(keys))
	for k := range keys {
		sorted = append(sorted, k)
	}
	sort.Strings(sorted)

	var reasons []string
	for _, key := range sorted {
		if reflect.DeepEqual(disk[key], regen[key]) {
			continue
		}
		if key == "run-args" && sameMultiset(disk[key], regen[key]) {
			reasons = append(reasons, "config.toml run-args are in an order booth config does not write"+
				" — add entries with --add-env / --add-expose / --add-mount instead")
			continue
		}
		reasons = append(reasons, fmt.Sprintf("config.toml `%s` could not be reproduced by any booth config flag", key))
	}
	return reasons
}

// compareBoothfile reports how the Boothfile on disk differs from the regenerated
// one, directive by directive; comments and blank lines do not count.
func compareBoothfile(diskContent, regenContent string) []string {
	disk := output.BoothfileDirectives(diskContent)
	regen := output.BoothfileDirectives(regenContent)
	if reflect.DeepEqual(disk, regen) {
		return nil
	}

	const shown = 5
	var reasons []string
	onlyDisk := multisetMinus(disk, regen)
	onlyRegen := multisetMinus(regen, disk)
	for i, line := range onlyDisk {
		if i == shown {
			reasons = append(reasons, fmt.Sprintf("Boothfile: … and %d more line(s)", len(onlyDisk)-shown))
			break
		}
		reasons = append(reasons, fmt.Sprintf("Boothfile `%s` — no selection or flag produces this line", line))
	}
	for i, line := range onlyRegen {
		if i == shown {
			reasons = append(reasons, fmt.Sprintf("Boothfile: … and %d more missing line(s)", len(onlyRegen)-shown))
			break
		}
		reasons = append(reasons, fmt.Sprintf("Boothfile `%s` — booth config writes this line but it was removed", line))
	}
	if len(reasons) == 0 {
		reasons = append(reasons, "Boothfile lines are in an order booth config does not write")
	}
	return reasons
}

// runArgPair is one run-args entry: a flag and its value, or a lone value.
type runArgPair struct {
	flag, value string
}

func (p runArgPair) canonicalFlag() string {
	if long, ok := runArgFlagForms[p.flag]; ok {
		return long
	}
	return p.flag
}

// key identifies the entry regardless of which form of the flag spells it.
func (p runArgPair) key() string {
	if p.flag == "" {
		return p.value
	}
	return p.canonicalFlag() + " " + p.value
}

func (p runArgPair) String() string {
	if p.flag == "" {
		return p.value
	}
	return p.flag + " " + p.value
}

// runArgPairs groups a run-args list the way the serializer writes it: a flag
// takes the value after it, anything else stands alone.
func runArgPairs(args []string) []runArgPair {
	var pairs []runArgPair
	for i := 0; i < len(args); i++ {
		if isRunArgFlag(args[i]) && i+1 < len(args) {
			pairs = append(pairs, runArgPair{flag: args[i], value: args[i+1]})
			i++
			continue
		}
		pairs = append(pairs, runArgPair{value: args[i]})
	}
	return pairs
}

func isRunArgFlag(s string) bool {
	return strings.HasPrefix(s, "-") && !strings.Contains(s, "=")
}

// canonicalizeRunArgs rewrites the run-args of a decoded config.toml to long-form
// flags in place, so the comparison does not tell `-e` from `--env`.
func canonicalizeRunArgs(cfg map[string]interface{}) {
	args, ok := stringList(cfg["run-args"])
	if !ok {
		return
	}
	var canonical []interface{}
	for _, pair := range runArgPairs(args) {
		if pair.flag != "" {
			canonical = append(canonical, pair.canonicalFlag())
		}
		canonical = append(canonical, pair.value)
	}
	cfg["run-args"] = canonical
}

// setsFromTOML spells a decoded config.toml value as the --set entries that write
// it back.
func setsFromTOML(key string, value interface{}) ([]string, error) {
	switch v := value.(type) {
	case bool:
		if v {
			return []string{key}, nil
		}
		return []string{key + "=false"}, nil
	case int64:
		return []string{fmt.Sprintf("%s=%d", key, v)}, nil
	case string:
		return []string{key + "=" + v}, nil
	case []interface{}:
		items, ok := stringList(v)
		if !ok {
			return nil, fmt.Errorf("`%s` is a list booth config cannot write back", key)
		}
		sets := make([]string, len(items))
		for i, item := range items {
			sets[i] = key + "=" + item
		}
		return sets, nil
	}
	return nil, fmt.Errorf("`%s` holds a value booth config cannot write back", key)
}

// dropSetsForKey removes every --set entry for key.
func dropSetsForKey(sets []string, key string) []string {
	var kept []string
	for _, set := range sets {
		if k, _, _ := strings.Cut(set, "="); k == key {
			continue
		}
		kept = append(kept, set)
	}
	return kept
}

func stringList(value interface{}) ([]string, bool) {
	if value == nil {
		return nil, true
	}
	items, ok := value.([]interface{})
	if !ok {
		return nil, false
	}
	list := make([]string, len(items))
	for i, item := range items {
		s, ok := item.(string)
		if !ok {
			return nil, false
		}
		list[i] = s
	}
	return list, true
}

func scalarString(value interface{}) string {
	if value == nil {
		return ""
	}
	return fmt.Sprintf("%v", value)
}

func sameMultiset(a, b interface{}) bool {
	la, okA := stringList(a)
	lb, okB := stringList(b)
	if !okA || !okB || len(la) != len(lb) {
		return false
	}
	return len(multisetMinus(la, lb)) == 0
}

// multisetMinus returns the items of a not matched, one for one, by an item of b.
func multisetMinus(a, b []string) []string {
	remaining := make(map[string]int, len(b))
	for _, item := range b {
		remaining[item]++
	}
	var out []string
	for _, item := range a {
		if remaining[item] > 0 {
			remaining[item]--
			continue
		}
		out = append(out, item)
	}
	return out
}

func readBoothFile(targetPath, name string) string {
	data, err := os.ReadFile(filepath.Join(targetPath, ".booth", name))
	if err != nil {
		return ""
	}
	return string(data)
}

// muteStderr points os.Stderr at the null device until the returned func runs.
func muteStderr() func() {
	devNull, err := os.OpenFile(os.DevNull, os.O_WRONLY, 0)
	if err != nil {
		return func() {}
	}
	saved := os.Stderr
	os.Stderr = devNull
	return func() {
		os.Stderr = saved
		devNull.Close()
	}
}

// boothBaseline is what a reconfigure starts from.
type boothBaseline struct {
	// flags is the recorded configuration — with the edits read back, if adopted.
	flags initFlags
	// drifted lists the guarded files still to be treated as hand-written: empty
	// when their edits were adopted.
	drifted []string
	// edited lists the guarded files found edited, adopted or not.
	edited []string
	adopt  adoptResult
}

// readBoothBaseline reads the existing booth at targetPath as a reconfigure's
// starting point, reading back any edits made to it since booth config wrote it.
// cli is this run's own flags; they only steer which templates the check uses.
func readBoothBaseline(version, targetPath string, cli initFlags) boothBaseline {
	baseline := boothBaseline{flags: readExistingBooth(targetPath)}
	baseline.edited = output.Drifted(targetPath)
	baseline.drifted = baseline.edited
	if len(baseline.edited) == 0 {
		return baseline
	}

	baseline.adopt = adoptEdits(version, targetPath, baseline.flags, cli)
	if baseline.adopt.adopted {
		baseline.flags = baseline.adopt.flags
		baseline.drifted = nil
	}
	return baseline
}

// printAdoptOutcome tells a --no-tui run what became of edits found in the booth:
// read back (and which comments a save removes), or why they could not be.
func printAdoptOutcome(w io.Writer, baseline boothBaseline) {
	if len(baseline.edited) == 0 || !baseline.adopt.attempted {
		return
	}
	files := ".booth/" + strings.Join(baseline.edited, ", .booth/")

	if baseline.adopt.adopted {
		verb := "was"
		if len(baseline.edited) > 1 {
			verb = "were"
		}
		fmt.Fprintf(w, "Note: %s %s edited outside booth config; the edits were read back and are kept.\n", files, verb)
		if lost := lostCommentsText(baseline.adopt.lost); lost != "" {
			fmt.Fprintf(w, "Warning: saving regenerates the files, which removes these comments:\n%s", lost)
		}
		return
	}

	fmt.Fprintf(w, "Could not read back the edits in %s:\n", files)
	for _, reason := range baseline.adopt.reasons {
		fmt.Fprintf(w, "  - %s\n", reason)
	}
	fmt.Fprintln(w)
}

// lostCommentsText lists comments a save removes, one per line, indented.
func lostCommentsText(lost []lostComment) string {
	var b strings.Builder
	for _, c := range lost {
		fmt.Fprintf(&b, "  %s:%d  %s\n", c.file, c.Line, c.Text)
	}
	return b.String()
}

// adoptReasonsText explains, for the hand-written dialog, why the edits could not
// be read back — or "" when there was nothing to try.
func adoptReasonsText(baseline boothBaseline) string {
	if !baseline.adopt.attempted || baseline.adopt.adopted || len(baseline.adopt.reasons) == 0 {
		return ""
	}
	var b strings.Builder
	b.WriteString("The edits could not be read back:\n\n")
	for _, reason := range baseline.adopt.reasons {
		b.WriteString("  - " + reason + "\n")
	}
	return strings.TrimRight(b.String(), "\n")
}
