# NOTE: This template has not been tested -- no time (sorry). Please report success or failure. :-p
display-name = "Cursor Credentials"
display-disc = "Mount ~/.cursor credentials from host (read-only home-seeding)"
auto-select = true
tags = ["cursor", "credential"]

run-args = [
    "-v", "~/.cursor:/etc/cb-home-seed/.cursor:ro"
]
