# NOTE: This template has not been tested -- no time (sorry). Please report success or failure. :-p
display-name = "Cursor Credentials"
display-disc = "Mount host Cursor editor credentials"
auto-select = true
tags = ["cursor", "credential"]

run-args = [
    "-v", "~/.cursor:/etc/cb-home-seed/.cursor:ro"
]
