run := if env("BOOTH_CONTAINER_NAME", "") == "" { "./booth exec --run --" } else { "" }

[private]
default:
    @just --list

# Compute a factorial (`just run 5`)
run *args:
    {{run}} ./run-factorial.sh {{ args }}
