run := if env("BOOTH_CONTAINER_NAME", "") == "" { "./booth exec --run --" } else { "" }

[private]
default:
    @just --list

# Wait for Floci, put a file in S3, and read it back
run:
    {{run}} ./demo.sh
