# NOTE: This template has not been tested -- no time (sorry). Please report success or failure. :-p
display-name = "Bash Config"
display-disc = "Seed ~/.bashrc from host"
display-order = 33
tags = [
    "bash",
    "shell",
    "config"
]

run-args = [
    "-v", "~/.bashrc:/etc/cb-home-seed/.bashrc:ro"
]
