# NOTE: This template has not been tested -- no time (sorry). Please report success or failure. :-p
display-name = "Scala VS Code Extension"
display-disc = "Scala language support extension for VS Code (Metals)"
display-order = 1
auto-select = true
tags = [
    "scala",
    "ide",
    "vscode",
]

[segments]
"Boothfile--65" = """
setup scala-code-extension
"""
