# Configured by: booth config --no-tui --overwrite --expose +-1920:80 --select php+composer~vscode-ext/mysql/apache+php/wp-init


run-args = [
    "-v", "booth-mysqldata:/var/lib/mysql",
    "--publish", "+-1920:80"
]
