# NOTE: This template has not been tested -- no time (sorry). Please report success or failure. :-p
display-name = "Kotlin VS Code Extension"
display-disc = "Kotlin language support extension for VS Code"
display-order = 1
auto-select = true
tags = [
    "kotlin",
    "ide",
    "vscode",
]

[segments]
"Boothfile--65" = """
setup kotlin-code-extension
"""
