display-name = "dive"
display-disc = "Explore Docker image layers and contents"
display-detail = "Installs dive, a TUI for exploring layers in a Docker image to discover space-saving opportunities. Pairs with docker-buildx and lazydocker."
display-order = 67
tags = [
    "docker",
    "container",
    "tui",
    "cli",
]

[params.DIVE_VERSION]
default = "latest"
suggests = ["latest"]

[segments]
Boothfile = """
setup dive --version ${DIVE_VERSION}
"""
