# NOTE: This template has not been tested -- no time (sorry). Please report success or failure. :-p
display-name = "Elixir VS Code Extension"
display-disc = "Elixir language support extension for VS Code"
display-order = 1
auto-select = true
tags = [
    "elixir",
    "ide",
    "vscode",
]

[segments]
"Boothfile--65" = """
setup elixir-code-extension
"""
