display-name = "VS Code"
primary = true
display-disc = "Visual Studio Code desktop IDE"
display-order = 10
tags = [
    "vscode",
    "ide",
    "editor"
]

[segments]
"Boothfile--60" = """
setup vscode
"""
