# Configured by: booth config --no-tui --overwrite --select rust+vscode-ext+kernel+cargo-pkg:ripgrep,fd-find,bat/python/notebook/xfce/claude-code


run-args = [
    "-e", "CARGO_NET_GIT_FETCH_WITH_CLI=true",
    "-v", "$HOME/.cargo/registry:/home/coder/.cargo/registry",
    "-v", "~/.cargo/credentials.toml:/etc/cb-home-seed/.cargo/credentials.toml:ro",
    "-e", "PYTHONDONTWRITEBYTECODE=1",
    "-v", "~/.config/pip:/etc/cb-home-seed/.config/pip:ro",
    "-v", "~/Library/Application Support/pip:/etc/cb-home-seed/.config/pip:ro",
    "-v", "~/AppData/Roaming/pip:/etc/cb-home-seed/.config/pip:ro",
    "-v", "~/.claude.json:/etc/cb-home-seed/.claude.json:ro",
    "-v", "~/.claude/.credentials.json:/etc/cb-home/.claude/.credentials.json:ro"
]
