# Configured by: booth config --no-tui --overwrite --expose +-1920:8080 --select java:21+maven:3.9.11+vscode-ext/nodejs


run-args = [
    "-v", "~/.npmrc:/etc/cb-home-seed/.npmrc:ro",
    "--publish", "+-1920:8080"
]
