# Configured by: booth config --no-tui --overwrite --expose +-7000:3000 --expose +-4827:5173 --select nodejs~vscode-ext/mongodb+start


run-args = [
    "-v", "~/.npmrc:/etc/cb-home-seed/.npmrc:ro",
    "-v", "booth-mongodata:/home/coder/.mongodb",
    "--publish", "+-7000:3000",
    "--publish", "+-4827:5173"
]
