run := if env("BOOTH_CONTAINER_NAME", "") == "" { "./booth exec --run --" } else { "" }

[private]
default:
    @just --list

# Package the Spring Boot app
build:
    {{run}} mvn -q package

# Run the web app on :8080
run:
    {{run}} mvn spring-boot:run
