display-name = "IntelliJ IDEA"
primary = true
display-disc = "JetBrains IntelliJ IDEA Community"
display-order = 20
tags = [
    "jetbrains",
    "idea",
    "ide",
    "java"
]

[segments]
"Boothfile--60" = """
setup idea
"""
