run := if env("BOOTH_CONTAINER_NAME", "") == "" { "./booth exec --run --" } else { "" }

[private]
default:
    @just --list

# Compile the Maven project
build:
    {{run}} mvn -q compile

# Clean, package, and run Person
run:
    {{run}} ./run-on-container.sh
