# NOTE: This template has not been tested -- no time (sorry). Please report success or failure. :-p
display-name = "AWS Credentials"
display-disc = "Mount ~/.aws credentials from host (read-only home-seeding)"
auto-select = true
tags = ["aws", "credential"]

run-args = [
    "-v", "~/.aws:/etc/cb-home-seed/.aws:ro"
]
