# NOTE: This template has not been tested -- no time (sorry). Please report success or failure. :-p
display-name = "Firebase Credentials"
display-disc = "Mount host Firebase CLI credentials into the booth"
display-order = 90
auto-select = true
tags = ["credential", "firebase"]

run-args = [
    # Firebase CLI credentials (home-seeding: may update tokens/session)
    "-v", "~/.config/configstore/firebase-tools.json:/etc/cb-home-seed/.config/configstore/firebase-tools.json:ro",
]
