run := if env("BOOTH_CONTAINER_NAME", "") == "" { "./booth exec --run --" } else { "" }

[private]
default:
    @just --list

# Greet a name (`just run World`, `just run -- --color Alice`)
run *args:
    {{run}} ./greeting.sh {{ args }}

# Run bun tests
test:
    {{run}} bun test
