display-name = "Ruby Notebook Kernel"
display-disc = "Ruby Jupyter notebook kernel (iruby)"
display-order = 5
auto-select = false
requires = ["notebook"]
tags = [
    "ruby",
    "kernel",
    "notebook"
]

[segments]
"Boothfile--70" = """
setup ruby-nb-kernel
"""
