[private]
default:
    @just --list

# Build the http-server image and start it
start:
    ./start-server.sh

# Stop the container
stop:
    ./stop-server.sh

# Check whether the server is up
check:
    ./check-server.sh
