# Configured by: booth config --no-tui --overwrite --expose +-5800:4200 --select nodejs~vscode-ext/mongodb+start


run-args = [
    "-v", "~/.npmrc:/etc/cb-home-seed/.npmrc:ro",
    "-v", "booth-mongodata:/home/coder/.mongodb",
    "--publish", "+-5800:4200"
]
