// Copyright 2025-2026 : Nawa Manusitthipol
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.

package output

import (
	"testing"

	"github.com/stretchr/testify/assert"
)

func TestSerializeBoothfile_Nil(t *testing.T) {
	result := SerializeBoothfile(nil)
	assert.Equal(t, "", result)
}

func TestSerializeBoothfile_EmptyContent(t *testing.T) {
	bf := &BoothfileContent{Content: ""}
	result := SerializeBoothfile(bf)
	assert.Equal(t, "", result)
}

func TestSerializeBoothfile_WithContent(t *testing.T) {
	bf := &BoothfileContent{
		Content: "setup python 3.12\nsetup go 1.24\n",
	}
	result := SerializeBoothfile(bf)
	assert.Contains(t, result, "# syntax=codingbooth/boothfile:1")
	assert.Contains(t, result, "# Generated by booth init")
	assert.Contains(t, result, "setup python 3.12")
	assert.Contains(t, result, "setup go 1.24")
}

func TestSerializeBoothfile_PreservesContent(t *testing.T) {
	content := "arg GO_VERSION=1.24\nsetup go ${GO_VERSION}\ninstall pip django\nenv APP_ENV=production\n"
	bf := &BoothfileContent{Content: content}
	result := SerializeBoothfile(bf)

	// Header should be present
	assert.Contains(t, result, "# syntax=codingbooth/boothfile:1")

	// Content should be at the end, verbatim
	assert.True(t, len(result) > len(content))
	assert.Contains(t, result, content)
}
