// Copyright 2025-2026 : Nawa Manusitthipol
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.

package output

import (
	"strings"
	"testing"

	"github.com/stretchr/testify/assert"
)

func TestSerializeConfigToml_Nil(t *testing.T) {
	result := SerializeConfigToml(nil, "", "")
	assert.Equal(t, "", result)
}

func TestSerializeConfigToml_Empty(t *testing.T) {
	cfg := &ConfigToml{}
	result := SerializeConfigToml(cfg, "", "")
	assert.Contains(t, result, "# Generated by booth init")
	// Should not contain any key-value pairs for empty fields
	assert.NotContains(t, result, "variant")
	assert.NotContains(t, result, "port")
	assert.NotContains(t, result, "dind")
}

func TestSerializeConfigToml_VariantOnly(t *testing.T) {
	cfg := &ConfigToml{
		Variant: "codeserver",
	}
	result := SerializeConfigToml(cfg, "", "")
	assert.Contains(t, result, `variant = "codeserver"`)
	assert.NotContains(t, result, "port")
}

func TestSerializeConfigToml_AllScalarFields(t *testing.T) {
	cfg := &ConfigToml{
		Variant:  "desktop-xfce",
		Port:     "NEXT",
		Timezone: "America/Toronto",
		Dind:     true,
	}
	result := SerializeConfigToml(cfg, "", "")
	assert.Contains(t, result, `variant = "desktop-xfce"`)
	assert.Contains(t, result, `port = "NEXT"`)
	assert.Contains(t, result, `timezone = "America/Toronto"`)
	assert.Contains(t, result, `dind = true`)
}

func TestSerializeConfigToml_DindFalseNotWritten(t *testing.T) {
	cfg := &ConfigToml{
		Variant: "base",
		Dind:    false,
	}
	result := SerializeConfigToml(cfg, "", "")
	assert.NotContains(t, result, "dind")
}

func TestSerializeConfigToml_CmdsSingleElement(t *testing.T) {
	cfg := &ConfigToml{
		Cmds: []string{"start-notebook"},
	}
	result := SerializeConfigToml(cfg, "", "")
	assert.Contains(t, result, `cmds = ["start-notebook"]`)
}

func TestSerializeConfigToml_CmdsMultipleElements(t *testing.T) {
	cfg := &ConfigToml{
		Cmds: []string{"bash", "-lc", "make test"},
	}
	result := SerializeConfigToml(cfg, "", "")
	assert.Contains(t, result, "cmds = [")
	assert.Contains(t, result, `"bash"`)
	assert.Contains(t, result, `"-lc"`)
	assert.Contains(t, result, `"make test"`)
}

func TestSerializeConfigToml_RunArgs(t *testing.T) {
	cfg := &ConfigToml{
		RunArgs: []string{"-e", "GOPROXY=https://proxy.golang.org,direct", "-v", "/mnt/data:/data"},
	}
	result := SerializeConfigToml(cfg, "", "")
	assert.Contains(t, result, "run-args = [")
	assert.Contains(t, result, `"-e"`)
	assert.Contains(t, result, `"GOPROXY=https://proxy.golang.org,direct"`)
}

func TestSerializeConfigToml_BuildArgs(t *testing.T) {
	cfg := &ConfigToml{
		BuildArgs: []string{"--no-cache"},
	}
	result := SerializeConfigToml(cfg, "", "")
	assert.Contains(t, result, `build-args = ["--no-cache"]`)
}

func TestSerializeConfigToml_FullConfig(t *testing.T) {
	cfg := &ConfigToml{
		Variant:   "codeserver",
		Port:      "NEXT",
		Timezone:  "Asia/Bangkok",
		Dind:      true,
		Cmds:      []string{"bash"},
		BuildArgs: []string{"--build-arg", "NODE_VERSION=20"},
		RunArgs:   []string{"-e", "TZ=Asia/Bangkok"},
	}
	result := SerializeConfigToml(cfg, "", "")

	// Verify ordering: scalar fields first, then arrays
	variantIdx := strings.Index(result, "variant")
	cmdsIdx := strings.Index(result, "cmds")
	buildArgsIdx := strings.Index(result, "build-args")
	runArgsIdx := strings.Index(result, "run-args")

	assert.True(t, variantIdx < cmdsIdx, "variant should come before cmds")
	assert.True(t, cmdsIdx < buildArgsIdx, "cmds should come before build-args")
	assert.True(t, buildArgsIdx < runArgsIdx, "build-args should come before run-args")
}

// --set override serialization

func TestSerializeConfigToml_WithBoolOverride(t *testing.T) {
	cfg := &ConfigToml{
		Variant:   "base",
		Overrides: map[string]interface{}{"keep-alive": true},
	}
	result := SerializeConfigToml(cfg, "", "")
	assert.Contains(t, result, `variant = "base"`)
	assert.Contains(t, result, "keep-alive = true")
}

func TestSerializeConfigToml_WithStringOverride(t *testing.T) {
	cfg := &ConfigToml{
		Overrides: map[string]interface{}{"name": "my-booth"},
	}
	result := SerializeConfigToml(cfg, "", "")
	assert.Contains(t, result, `name = "my-booth"`)
}

func TestSerializeConfigToml_WithFalseOverride(t *testing.T) {
	cfg := &ConfigToml{
		Overrides: map[string]interface{}{"daemon": false},
	}
	result := SerializeConfigToml(cfg, "", "")
	assert.Contains(t, result, "daemon = false")
}

func TestSerializeConfigToml_OverridesSorted(t *testing.T) {
	cfg := &ConfigToml{
		Overrides: map[string]interface{}{
			"name":       "test",
			"keep-alive": true,
			"daemon":     false,
		},
	}
	result := SerializeConfigToml(cfg, "", "")
	daemonIdx := strings.Index(result, "daemon")
	keepAliveIdx := strings.Index(result, "keep-alive")
	nameIdx := strings.Index(result, "name")
	assert.True(t, daemonIdx < keepAliveIdx, "daemon should come before keep-alive")
	assert.True(t, keepAliveIdx < nameIdx, "keep-alive should come before name")
}

func TestSerializeConfigToml_OverridesAfterKnownFields(t *testing.T) {
	cfg := &ConfigToml{
		Variant:   "base",
		Port:      "8080",
		Overrides: map[string]interface{}{"keep-alive": true},
	}
	result := SerializeConfigToml(cfg, "", "")
	portIdx := strings.Index(result, "port")
	keepAliveIdx := strings.Index(result, "keep-alive")
	assert.True(t, portIdx < keepAliveIdx, "known fields should come before overrides")
}

func TestSerializeConfigToml_NoOverrides(t *testing.T) {
	cfg := &ConfigToml{
		Variant: "base",
	}
	result := SerializeConfigToml(cfg, "", "")
	assert.NotContains(t, result, "keep-alive")
}

func TestSerializeConfigToml_EmptyOverrides(t *testing.T) {
	cfg := &ConfigToml{
		Variant:   "base",
		Overrides: map[string]interface{}{},
	}
	result := SerializeConfigToml(cfg, "", "")
	// Should have no trailing blank line from empty overrides
	lines := strings.Split(strings.TrimRight(result, "\n"), "\n")
	lastLine := lines[len(lines)-1]
	assert.NotEqual(t, "", lastLine, "should not end with blank line from empty overrides")
}

func TestSerializeConfigToml_CacheFilesSingle(t *testing.T) {
	cfg := &ConfigToml{
		CacheFiles: []string{"home/coder/.custom_history"},
	}
	result := SerializeConfigToml(cfg, "", "")
	assert.Contains(t, result, `cache-files = ["home/coder/.custom_history"]`)
}

func TestSerializeConfigToml_CacheFilesMultiple(t *testing.T) {
	cfg := &ConfigToml{
		CacheFiles: []string{"home/coder/.bash_history", "home/coder/.zsh_history"},
	}
	result := SerializeConfigToml(cfg, "", "")
	assert.Contains(t, result, "cache-files = [")
	assert.Contains(t, result, `"home/coder/.bash_history"`)
	assert.Contains(t, result, `"home/coder/.zsh_history"`)
}

func TestSerializeConfigToml_CacheDirsSingle(t *testing.T) {
	cfg := &ConfigToml{
		CacheDirs: []string{"home/coder/.mozilla"},
	}
	result := SerializeConfigToml(cfg, "", "")
	assert.Contains(t, result, `cache-dirs = ["home/coder/.mozilla"]`)
}

func TestSerializeConfigToml_CacheDirsMultiple(t *testing.T) {
	cfg := &ConfigToml{
		CacheDirs: []string{"home/coder/.local/share/nvim", "home/coder/.local/state/nvim"},
	}
	result := SerializeConfigToml(cfg, "", "")
	assert.Contains(t, result, "cache-dirs = [")
	assert.Contains(t, result, `"home/coder/.local/share/nvim"`)
	assert.Contains(t, result, `"home/coder/.local/state/nvim"`)
}

func TestSerializeConfigToml_CacheFilesAndDirs(t *testing.T) {
	cfg := &ConfigToml{
		CacheFiles: []string{"home/coder/.irb_history"},
		CacheDirs:  []string{"home/coder/.mongosh"},
	}
	result := SerializeConfigToml(cfg, "", "")
	assert.Contains(t, result, `cache-files = ["home/coder/.irb_history"]`)
	assert.Contains(t, result, `cache-dirs = ["home/coder/.mongosh"]`)
	// cache-files should come before cache-dirs
	filesIdx := strings.Index(result, "cache-files")
	dirsIdx := strings.Index(result, "cache-dirs")
	assert.True(t, filesIdx < dirsIdx, "cache-files should come before cache-dirs")
}

func TestSerializeConfigToml_CacheBeforeOverrides(t *testing.T) {
	cfg := &ConfigToml{
		CacheFiles: []string{"home/coder/.custom"},
		Overrides:  map[string]interface{}{"keep-alive": true},
	}
	result := SerializeConfigToml(cfg, "", "")
	cacheIdx := strings.Index(result, "cache-files")
	overrideIdx := strings.Index(result, "keep-alive")
	assert.True(t, cacheIdx < overrideIdx, "cache-files should come before overrides")
}

func TestSerializeConfigToml_EmptyCacheNotWritten(t *testing.T) {
	cfg := &ConfigToml{
		Variant: "base",
	}
	result := SerializeConfigToml(cfg, "", "")
	assert.NotContains(t, result, "cache-files")
	assert.NotContains(t, result, "cache-dirs")
}

func TestSerializeConfigToml_ValidToml(t *testing.T) {
	cfg := &ConfigToml{
		Variant: "codeserver",
		Port:    "8080",
		RunArgs: []string{"-e", "KEY=value with spaces"},
	}
	result := SerializeConfigToml(cfg, "", "")

	// Verify scalar key=value lines have properly quoted string values.
	// Skip comment lines, blank lines, array brackets, and array element lines.
	lines := strings.Split(result, "\n")
	for _, line := range lines {
		line = strings.TrimSpace(line)
		if line == "" || strings.HasPrefix(line, "#") ||
			strings.HasPrefix(line, "]") || strings.HasPrefix(line, `"`) {
			continue
		}
		// Only check top-level scalar assignments (key = value)
		if strings.Contains(line, " = ") {
			parts := strings.SplitN(line, " = ", 2)
			if len(parts) == 2 {
				key := strings.TrimSpace(parts[0])
				val := strings.TrimSpace(parts[1])
				// Skip array headers like "run-args = ["
				if strings.HasPrefix(val, "[") {
					continue
				}
				// Boolean values don't need quoting
				if val == "true" || val == "false" {
					continue
				}
				assert.True(t, strings.HasPrefix(val, `"`),
					"scalar value for %q should be quoted: %s", key, line)
			}
		}
	}
}
