// Copyright 2025-2026 : Nawa Manusitthipol
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.

package output

import "fmt"

// formatGeneratedHeader produces the comment header for generated files.
// When command and adjustCommand are provided, it produces two lines:
//
//	# Generated by: booth init new --version 0.21.0 --select go/zig
//	# Adjust with : booth init adjust --version 0.21.0 --select go/zig
//
// When both are empty, it falls back to a generic header:
//
//	# Generated by booth init
func formatGeneratedHeader(prefix, command, adjustCommand string) string {
	if command == "" && adjustCommand == "" {
		return fmt.Sprintf("%s Generated by booth init\n", prefix)
	}
	var s string
	if command != "" {
		s += fmt.Sprintf("%s Generated by: %s\n", prefix, command)
	}
	if adjustCommand != "" {
		s += fmt.Sprintf("%s Adjust with : %s\n", prefix, adjustCommand)
	}
	return s
}
