// Copyright 2025-2026 : Nawa Manusitthipol
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.

package output

import "fmt"

// formatGeneratedHeader produces the comment header for generated files.
// When adjustCommand is provided, it produces a single line:
//
//	# Configured by: booth config --no-tui --overwrite --select go/zig
//
// When both are empty, it falls back to a generic header:
//
//	# Generated by booth init
func formatGeneratedHeader(prefix, command, adjustCommand string) string {
	if command == "" && adjustCommand == "" {
		return fmt.Sprintf("%s Generated by booth init\n", prefix)
	}
	if adjustCommand != "" {
		return fmt.Sprintf("%s Configured by: %s\n", prefix, adjustCommand)
	}
	return fmt.Sprintf("%s Configured by: %s\n", prefix, command)
}
