// Copyright 2025-2026 : Nawa Manusitthipol
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.

package output

import "strings"

// Comment is one comment found in a guarded file: the 1-based line it sits on and
// its text from the "#" on, trimmed.
type Comment struct {
	Line int
	Text string
}

// ownedCommentPrefixes are the comments booth config writes itself on every
// generation — the syntax directive and the provenance header. They are rewritten,
// never carried, so they are not anyone's comment to lose.
var ownedCommentPrefixes = []string{
	"# syntax=",
	"# Configured by:",
	"# Generated by",
	"# Adjust with",
}

func isOwnedComment(text string) bool {
	for _, prefix := range ownedCommentPrefixes {
		if strings.HasPrefix(text, prefix) {
			return true
		}
	}
	return false
}

// BoothfileComments returns the full-line comments in a Boothfile, skipping the
// ones booth config owns. A "#" later in a line is not a comment there — it is part
// of the directive (a shell command, a URL fragment) — so only whole lines count.
func BoothfileComments(content string) []Comment {
	var comments []Comment
	for i, line := range strings.Split(content, "\n") {
		trimmed := strings.TrimSpace(line)
		if strings.HasPrefix(trimmed, "#") && !isOwnedComment(trimmed) {
			comments = append(comments, Comment{Line: i + 1, Text: trimmed})
		}
	}
	return comments
}

// BoothfileDirectives returns a Boothfile's directive lines — comments and blank
// lines dropped, surrounding whitespace trimmed, order kept. Two Boothfiles with
// equal directives build the same image, whatever their comments or spacing.
func BoothfileDirectives(content string) []string {
	var directives []string
	for _, line := range strings.Split(content, "\n") {
		trimmed := strings.TrimSpace(line)
		if trimmed == "" || strings.HasPrefix(trimmed, "#") {
			continue
		}
		directives = append(directives, trimmed)
	}
	return directives
}

// ConfigTomlComments returns the comments in a config.toml — whole-line ones and
// ones trailing a value (`port = "10080"  # team port`) — skipping the ones booth
// config owns. A "#" inside a quoted string is not a comment.
func ConfigTomlComments(content string) []Comment {
	var comments []Comment
	for i, line := range strings.Split(content, "\n") {
		start := tomlCommentStart(line)
		if start < 0 {
			continue
		}
		text := strings.TrimSpace(line[start:])
		if !isOwnedComment(text) {
			comments = append(comments, Comment{Line: i + 1, Text: text})
		}
	}
	return comments
}

// tomlCommentStart returns the index of the "#" that starts a comment on line, or
// -1. It tracks basic ("…", with backslash escapes) and literal ('…') strings on the
// line; a multi-line string spanning lines is not something booth config writes.
func tomlCommentStart(line string) int {
	var quote byte
	for i := 0; i < len(line); i++ {
		c := line[i]
		switch {
		case quote == '"' && c == '\\':
			i++
		case quote != 0:
			if c == quote {
				quote = 0
			}
		case c == '"' || c == '\'':
			quote = c
		case c == '#':
			return i
		}
	}
	return -1
}

// LostComments returns the comments of before that after does not carry — each
// comment matched at most once, by text, so a comment that appears twice before and
// once after still reports one loss.
func LostComments(before, after []Comment) []Comment {
	remaining := make(map[string]int, len(after))
	for _, c := range after {
		remaining[c.Text]++
	}
	var lost []Comment
	for _, c := range before {
		if remaining[c.Text] > 0 {
			remaining[c.Text]--
			continue
		}
		lost = append(lost, c)
	}
	return lost
}
