// Copyright 2025-2026 : Nawa Manusitthipol
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.

package output

import (
	"testing"

	"github.com/stretchr/testify/assert"
)

func TestSerializeStartup_Nil(t *testing.T) {
	result := SerializeStartup(nil)
	assert.Equal(t, "", result)
}

func TestSerializeStartup_EmptyContent(t *testing.T) {
	sc := &StartupContent{Content: ""}
	result := SerializeStartup(sc)
	assert.Equal(t, "", result)
}

func TestSerializeStartup_WithContent(t *testing.T) {
	sc := &StartupContent{
		Content: "echo \"Starting up...\"\n/opt/myapp/init.sh\n",
	}
	result := SerializeStartup(sc)
	assert.Contains(t, result, "#!/bin/bash")
	assert.Contains(t, result, "set -e")
	assert.Contains(t, result, "# Generated by booth init")
	assert.Contains(t, result, `echo "Starting up..."`)
	assert.Contains(t, result, "/opt/myapp/init.sh")
}

func TestSerializeStartup_PreservesContent(t *testing.T) {
	content := "# Initialize database\n/opt/db/migrate.sh\n\n# Start service\n/opt/svc/start.sh\n"
	sc := &StartupContent{Content: content}
	result := SerializeStartup(sc)
	assert.Contains(t, result, content)
}
