[private]
default:
    @just --list

# Compile the FizzBuzz binary
build:
    cargo build

# Run FizzBuzz (default range 1–15)
run *args:
    ./run-fizzbuzz.sh {{ args }}

# Run cargo tests
test:
    ./run-rust-test.sh
