run := if env("BOOTH_CONTAINER_NAME", "") == "" { "./booth exec --run --" } else { "" }

[private]
default:
    @just --list

# Compile the FizzBuzz binary
build:
    {{run}} cargo build

# Run FizzBuzz (default range 1–15)
run *args:
    {{run}} ./run-fizzbuzz.sh {{ args }}

# Run cargo tests
test:
    {{run}} ./run-rust-test.sh
